### ISSUE TITLE
No specific z-wave parameters settings for FGMS-001

### ISSUE THREAD

**Issue by ralfvd** [athombv/com.fibaro#1]
**What is your Homey version (Settings → System)?**

0.9.1

**What is your App version **

1.0.2

**What did you try to achieve?**

Add specific parameters:

42 - Lummination report interval
80 - Led signal mode
89 - Tamper alarm led indication

**What was the result?**

No option to set parameters

**What did you expect as result?**

As in previous version Z-wave implementation, a way to set config parameters to alter device's behaviour. 
 
**Any other remarks**

Suggestion: build a hybrid solution: select/pull-down menus for the most popular used, but an advanced selection to manually enter the config parameters (e.g. 20,1,1;22,1,1)

![screen shot 2016-07-29 at 19 37 48](https://cloud.githubusercontent.com/assets/17275712/17257798/040157ec-55c4-11e6-833c-2215e90ef174.png)

**Comment by 2benl** [comment]
Some goes for the Z-wave plus FGMS-001-ZW5 version.

**Comment by djefmo** [comment]
Like @2benl mentioned; it's also not working for me. There is no option to change the config parameters. Hope this will be added soon. Same goes for the dimmer and relay support...

**Comment by njreus** [comment]
I agree. I have two Fibaro dimmers and a relay switch. Unfortunately, Homey's Fibaro app currently does not support these switches. In addition, I had to reconnect them to Homey but was only successful in connecting the Relay Switch. However, I have to set a data parameter to 14,1,0 for the switch to properly work (also see https://forum.athom.com/discussion/728/fibaro-relay-switch#latest); unfortunately, this is not possible anymore.

**Comment by ralfvd** [comment]
Settings are now available.
