### ISSUE TITLE
Dimmer 1 (FDG-211) added as unknown z-wave device

### ISSUE THREAD

**Issue by irritanterik** [athombv/com.fibaro#10]
Added a build-in dimmer FDG-211 via generic z-wave addition screen:
![image](https://cloud.githubusercontent.com/assets/15232724/17269128/d0b16026-5640-11e6-9860-885344014c4b.png)

On pairing it reports that this is a unsupported device / no apps found:
![image](https://cloud.githubusercontent.com/assets/15232724/17269132/e3d0bdf0-5640-11e6-88bf-2cea8c7f6fcc.png)

Settings shows this information:
![image](https://cloud.githubusercontent.com/assets/15232724/17269135/ee365a02-5640-11e6-8651-b08e657ba387.png)

**Comment by irritanterik** [comment]
Ah a pull request available allready: https://github.com/athombv/com.fibaro/pull/8

**Comment by swttt** [comment]
And merged ;) 
Note i didn't add allot of settings (yet) tho, i think you can close this now ;)

**Comment by Robinyoh** [comment]
Is there also coming support for Dimmer 2 FGD-212?

**Comment by swttt** [comment]
@Robinyoh I don't have a Dimmer 2, so can't help you with that. I might just work the same tho, so most of the code in this driver could be re-used.
