### ISSUE TITLE
LED for FGWPE/F-102 not working anymore

### ISSUE THREAD

**Issue by Tweaqer** [athombv/com.fibaro#100]
Hi there,
For some reason the led stopped working for this type of wallplug. It's stuffed away abit so I just noticed it today but it could have stopped working earlier. I have some more fibaro wallplugs (FGWPx-102-PLUS and a FGWPx-101) that do work fine but they are different versions and for this version (FGWPE/F-102) it doesn't work anymore. I tried changing the led parameter values in the settings but that did not have any effect. I also ruled out a broken led because it lights up when I plug it in but after that it turns off and doesnt turn back on. It doesn't respond to usage and it doesnt matter if it's on or off.
Hope you can fix it, let me know if you need more info
Cheers

**Comment by caseda** [comment]
Did you re-pair it to homey already? Like you, mentioned you wanted to do

**Comment by Tweaqer** [comment]
I decided to do a full reset of the wallplug and that worked, thanks! :)
