### ISSUE TITLE
FGS-223: Power measurement on S2 fails after some time

### ISSUE THREAD

**Issue by philsniff** [athombv/com.fibaro#101]
after a clean inclusion of the Double Switch 2 (FGS-223) the Power Measurement ist displayed on S1 and S2 linke it should. i have the swiitch in my hallway within a cross circuit (three switches) and use s1 and S2 for realize crossover switch. all works perfect!

but in this case i have to check the power of the switches because if i switch another switch the lights could be off/on but the FGS didn't changed its state (normal in a cross circuit)  

so i want to know if electicity is there to make my lights on (S1 or S2 have power) or if the lights are all off (s1 and s2 have no power!)

but my problem is that s2 'forgets' to report power after some time (i think after 1 hour or 2 hours, feels like). i removed the fgs-223 three or four times and did the inclusion again. right after that the s2 showed the power again. but not for long.

it seems that the interview of the device for the inclusion brings the powermeasurement to the s2, but after some time it fails....

did i expressed my matter for you clearly? i did my best :-)

**Comment by RobinBol** [comment]
Hi, just a question to understand your problem. Is there any power in/out connected to the FGS-223 S2 that is not reporting power consumption? Or is it merely acting as a switch (not actually switching anything hardwired)?

**Comment by caseda** [comment]
The s2's meter cc just sends 0 as value once in a while even when there is a load attached.

There is a forum post about this somewhere. 

So not really something we can do about, and trying to filter that out is kinda hard to do and also keep it responsive

**Comment by RobinBol** [comment]
I've read the forum post and indeed this is not something Homey can fix. It seems the device is sending merely zero values, why is unknown to me.

I'll close this issue, you might want to ask Fibaro support about your problem.
