### ISSUE TITLE
Dimmer icon not working correctly (need to click it twice to switch the light off)

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/com.fibaro#102]
**What is your Homey version (Settings → System)?**
1.1.4

**What did you try to achieve?**
Switch off the light (dimmer)

**Please include detailed steps how we can reproduce the issue**
When you change the dim value with the slider the light goes on but the color of the slider stays gray. ("off" status but the light is on)
![image](https://cloud.githubusercontent.com/assets/17165733/22618271/73d46358-ead8-11e6-8d00-877cc06a7452.png)

So for switching the light off I first have to click on the dimmer icon to make it solid black ("on" status and the light stays on)
![image](https://cloud.githubusercontent.com/assets/17165733/22618272/7ed4e890-ead8-11e6-939d-5509db07bb48.png)

And than click the icon again to turn the light off and the color of the icon and sliders changes back to gray again.

**What was the result?**
Need to click the dimmer icon twice to switch the light off when you have used the slider to change the dimmer value (which also turns the light on).

**What did you expect as result?**
- That when using the slider to change the dimmer value r and the light switches on that the dimmer icon goes into the "on" status (solid black color)

- Or when changing the dimmer value using the slider the light stays off until you click on the dimmer icon.

**Any other remarks**
I have tested this with the Duwi built-in dimmer - 05433 and the Z-Wave.Me app

**Comment by caseda** [comment]
why is this in the fibaro app's repository?
and not in the app's [repository](https://github.com/IcarusProject/me.zwave)?

**Comment by JesperJanssen** [comment]
Sorry for that. Have moved it to the default Homey topic (think it's a general Homey issue)
