### ISSUE TITLE
My Binairy Sensor, Device ID 265, is not recognized.

### ISSUE THREAD

**Issue by JPe2** [athombv/com.fibaro#113]
![clipboarder 2017 02 22](https://cloud.githubusercontent.com/assets/3833862/23216167/4fdbbe9c-f915-11e6-9894-b0729af00b15.png)

Acording to "Pepper" the  productId value="0102"
my device reports   265  =   hex  0109   ????

**Comment by RobinBol** [comment]
Added your productId to the fibaro app, in a coming update your device will be supported.
