### ISSUE TITLE
Smoke sensor z-wave + (v2) sensors missing

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/com.fibaro#12]
**What is your Homey version (Settings → System)?**
Homey Firmware Version: 0.9.1
Fibaro App Version: 1.0.2

**What did you try to achieve?**

Add the Fibaro Smoke Sensor Z-Wave + (v2) but i am missing sensors.
![knipsel](https://cloud.githubusercontent.com/assets/8224586/17270408/46bb210a-5662-11e6-80e4-1df66487c42d.PNG)

And device specific settings like wake up interval or sensor Sensitivity 
![knipsel](https://cloud.githubusercontent.com/assets/8224586/17270424/7e47204c-5662-11e6-8d87-2b1f89b3acee.PNG)

**Please include detailed steps how we can reproduce the issue**

Add fibaro smoke sensor z-wave plus (v2) and after that the sensors are missing

**What was the result?**

**What did you expect as result?**

To trigger flows from Homey from the sensors of the  Fibaro Smoke Sensor Z-Wave + (v2)

**Comment by caseda** [comment]
#5 duplicate

**Comment by WeeJeWel** [comment]
Should be fixed
