### ISSUE TITLE
Feature request Dimmer 2 - trigger card for light intensity

### ISSUE THREAD

**Issue by robiebab** [athombv/com.fibaro#123]
it would be nice to have a feature in the "if" and "and" collum of the flow, to set a trigger for a certain light intensity of the dimmer 2.

for example: **if** light intenisity changes **and** dimmer light intensity = 0.2 **then** set dimmer to light intensity = 0.6

**Comment by caseda** [comment]
You can already use the logic cards for that "is higher then" / "is lower then" with the global tag or the trigger card's tag
