### ISSUE TITLE
Feature request - Update fibaro devices firmware 

### ISSUE THREAD

**Issue by robiebab** [athombv/com.fibaro#127]
i would like to see an update methode for the fibaro devices

**Comment by Veldkornet** [comment]
I don't know how often the devices get firmware updates, but I agree that that this would be ideal if Homey could handle this process.

**Comment by caseda** [comment]
Fibaro devices won't get updates that regularly.

But even if they give out an update, there is a big chance we are not able to get that update information (the normal way at least), as fibaro is pretty good at keeping it to themselves at the moment.

**Comment by RobinBol** [comment]
We discussed this, but it is not likely to happen in the near future, we foresee too many issue with updating firmware. Next to that, devices do not receive updates too often. Will close this issue for now.
