### ISSUE TITLE
Smoke sensor is not triggering any flow

### ISSUE THREAD

**Issue by camilleversteeg** [athombv/com.fibaro#128]
What is your Homey version (Settings → System)?

Homey Firmware Version: 1.2.0-rc.10

What did you try to achieve?

Trigger a flow when the Fibaro Smoke Sensor detects smoke.

What did you expect as result?

The flow to be executed.

Any other remarks

I'm not the only person with this issue: https://forum.athom.com/discussion/2952/fibaro-smoke-sensor-doenst-trigger-my-homey-scene

Screenshots:

![image](https://cloud.githubusercontent.com/assets/15101655/24578763/af42cb4c-16e7-11e7-9233-8ab83bee8e33.png)

The smoke detection and Heat Alarm are always empty.

This is the flow:

![image](https://cloud.githubusercontent.com/assets/15101655/24578770/ce04da84-16e7-11e7-8ab6-7a8e0164540c.png)

This is the device:

![image](https://cloud.githubusercontent.com/assets/15101655/24578775/05dcafb8-16e8-11e7-831e-3abfaf702205.png)

Z-wave log:

![image](https://cloud.githubusercontent.com/assets/15101655/24578772/eaa4a5de-16e7-11e7-9562-616fef9ec673.png)

**Comment by glijie** [comment]
Same issue here,

Flows are not triggered and insights doesn't show any changes. Only temperatuur shows any changes.

**Comment by CyberSponk** [comment]
Same Issue on App-Version 1.4.1!

**Comment by RobinBol** [comment]
Fixed in v1.4.3, please re-open if you are still experiencing issues.
