### ISSUE TITLE
Add support for Scene Activation Command Class

### ISSUE THREAD

**Issue by swttt** [athombv/com.fibaro#13]
Debug doesn't show the scene_activation class.
The dimmer v1 and the Door/Window sensor both support the scene_activation command.

Looks like you forgot to add support for it eventually...

**Comment by WeeJeWel** [comment]
Both the Dimmer and Contact sensor do not support the COMMAND_CLASS_SCENE_ACTIVATION. However, they do 'Control' it, which in Z-Wave terms is 'relay information to nodes that do support it'.

So Homey cannot do anything with them. If I'm mistaken, please let me know :-)

**Comment by swttt** [comment]
If i am right, the dimmer should be able to send a "scene_activation" to the controller (homey in this case). Homey picks this up, and starts a flow. It works this way in openhab (https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveSceneActivationCommandClass.java)

I don't think fibaro is the only one with this issue. Some z-wave remotes use the same way (Aeon Minimote).

So i do think there is a way to get it to work, but i am not sure how :)

**Comment by irritanterik** [comment]
S2 is a big deal on dimmers V1 and v2. In my house I have several build in modules with double momentary switches. The second button is used to switch lights or activate scenes.
It would be hard to explain why this functionality is supported by non fibaro controllers like Homeseer and Domoticz , but not by Homey.

**Comment by irritanterik** [comment]
Scene activation is still a very powerfull function, essential for advanced use cases. Like with the fibaro button. Scene activation frames are send to the controller with parameter values according to every scene activation device manual.

**Comment by SergeRegoor** [comment]
I'd love scene activation, too.

**Comment by WeeJeWel** [comment]
This has been added in the newest Homey firmware (0.8.17)

**Comment by caseda** [comment]
@WeeJeWel 
Now add the dimming duration of scene activation as well so we can use it in the dimmer 2 too :D

**Comment by SergeRegoor** [comment]
Can't get scene activation to work in the FGD-212 device (Dimmer 2).
I've added setting 28 as checkbox, which should enable scene activation for the device.

With the following code in the driver I would expect some debug logging in the console when a button is clicked.


```
module.exports.on('initNode', token => {
	const node = module.exports.nodes[token];
	if (node) {
		node.instance.CommandClass['COMMAND_CLASS_BASIC'].on('report', (command, report) => {
			Homey.log('COMMAND_CLASS_BASIC report');
			Homey.log(report);
			if (report['Value'] <= 0 || report['Value'] >= 255) {
				Homey.manager('flow').triggerDevice('FGD-212_s2', null, null, node.device_data);
			} else {
				Homey.manager('flow').triggerDevice('FGD-212_long_s2', null, null, node.device_data);
			}
		});
		
		Homey.log('my custom init');
		
		node.instance.CommandClass['COMMAND_CLASS_SCENE_ACTIVATION'].on('report', (command, report) => {
			Homey.log('report');
			Homey.log(command);
			Homey.log(report);
			
			if (command.name === 'SCENE_ACTIVATION_SET') {
				Homey.log('Joehoe!');
			}
		});
	}
});

```

**Comment by caseda** [comment]
Already told you it didn't work ;) 
and already had a github issue about it:
https://github.com/athombv/homey/issues/1033

Oh well

**Comment by RobinBol** [comment]
Will close this issue as scene activation is implemented at the moment.
