### ISSUE TITLE
smoke sensor zw plus no battery

### ISSUE THREAD

**Issue by satbopper** [athombv/com.fibaro#132]
with homey rc10 firmware and fibaro 1.4.1 even after three times the button on the sensor,there is no battery given on the device

**Comment by RobinBol** [comment]
You might have to wait for longer than the wake up period before the device sends a battery update. Wait 1-2 days if there is then still no battery reading please let me know!

**Comment by satbopper** [comment]
still no battery on the device i"m afraid

**Comment by satbopper** [comment]
the install of rc12 brought it back,scheelt weer,goodluck

**Comment by camilleversteeg** [comment]
I'm not getting any battery updates, but i'll wait for a couple of days i guess.

**Comment by camilleversteeg** [comment]
@satbopper what did you do to get the battery working. Its been a few days since i've installed rc12, but no battery:

![image](https://cloud.githubusercontent.com/assets/15101655/24996918/01443d6c-2035-11e7-9998-2038a78430cb.png)
