### ISSUE TITLE
Energy usage not visible for double switch v2

### ISSUE THREAD

**Issue by jaimevisser** [athombv/com.fibaro#136]
I have a couple of double relay switches configured as lights. These do not show power usage (W, Kwh) in the homey app (insights and cards) and android mobile app. Is this feature currently not working? This used to work in domoticz.

**Comment by caseda** [comment]
possibly the same as a closed issue?:
https://github.com/athombv/com.fibaro/issues/101

even though that was only for wattage

**Comment by RobinBol** [comment]
Do they show zero's or dashes?

**Comment by jaimevisser** [comment]
Nothing is shown on cards (not even - kwh / - W), no insights are logged.

Card of "ventilation" switch:
![screen shot 2017-04-16 at 14 28 03](https://cloud.githubusercontent.com/assets/3132806/25071182/0c01fbe4-22b1-11e7-815a-3dd939550c1f.png)

Card of "light" switch:
![screen shot 2017-04-16 at 14 28 27](https://cloud.githubusercontent.com/assets/3132806/25071184/10c08a6a-22b1-11e7-8e0f-d07bd38f8175.png)

Insights not logged:
![screen shot 2017-04-16 at 14 28 54](https://cloud.githubusercontent.com/assets/3132806/25071186/141dd618-22b1-11e7-9fe1-fdb86c742468.png)

**Comment by RobinBol** [comment]
If you do not add them as "lights" the power measurements will show, please let me know if that fixes it for you!

**Comment by jaimevisser** [comment]
Will test tomorrow and let you know. If only there were some way of changing the type without re-adding a device.

**Comment by RobinBol** [comment]
Did it work?

**Comment by jaimevisser** [comment]
Didn't work. Removed the Double Relay Switch 2 from homey and re-added it. Still shows only on/off switch and no power usage.

**Comment by caseda** [comment]
Ah, the Double **Relay** Switch 2 (that's something you did not mention before)

the relay versions don't have any power measuring,
only the double switch 2, single switch 2 and dimmer 2 do that for the in wall modules

**Comment by jaimevisser** [comment]
Must have some Double Switch 2 and some Relay Switches 2 in use? Not really much of an issue as we'll get new modules for our next house (under construction).

**Comment by RobinBol** [comment]
Will close this issue as it seems the device does not report any power measurements.
