### ISSUE TITLE
Fibaro Wall Plug 2 Usage As Lamp

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.fibaro#141]
When I had my Fibaro Wall Plug 2 configured as "just a plug", I was able to see de watt Usage etc on the device card on the device page. 

However, if I add the Wall Plug as a "lamp" type, I do not see this and I can only turn it off and on. 

Why is this? Is it a bug? Can you fix this? Functionally, the device does not operate any differently to me, only now I can no longer see the usage on the card.

**Comment by caseda** [comment]
Already told you in the form that it is fixed in homey fw 1.3 :wink:

**Comment by Veldkornet** [comment]
Oh, sorry, I didn't see that :P But thanks!
