### ISSUE TITLE
[Device Support] Fibaro Door & Window Sensor (version 2)

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.fibaro#145]
Could we get support added for the Fibaro Door & Window Sensor (version 2), it's the one with the built in thermometer.

I tried to add it using the current Door / Window sensor (Z Wave Plus), but it always hangs on the screen "Fetching Wakeup Period", and then times out.

![screen shot 2017-05-30 at 18 59 11](https://cloud.githubusercontent.com/assets/10297361/26595255/1f40b0ec-456b-11e7-912f-23e5e5c57cb6.png)

![screen shot 2017-05-30 at 18 59 28](https://cloud.githubusercontent.com/assets/10297361/26595260/2530c03c-456b-11e7-90b8-12e6d2dad23b.png)

![screen shot 2017-05-30 at 19 15 43](https://cloud.githubusercontent.com/assets/10297361/26595610/4ab4fe26-456c-11e7-950d-e1698464aaf0.png)

**Comment by Veldkornet** [comment]
Node Information

![screen shot 2017-05-30 at 20 13 40](https://cloud.githubusercontent.com/assets/10297361/26598092/6a6fbbe0-4574-11e7-9993-5a8c296f34d0.png)

**Comment by caseda** [comment]
I tried adding it (have 2 myself) but the device doesn't give the wakeup time when asking for it during inclusion, have already notified @WeeJeWel and he would buy the device and look at it more carefully since it response differently then all other devices.

Have not seen/heard from it (didn't ask either), but hé he's a busy man :smile:

**Comment by Veldkornet** [comment]
Hmm, well I added it as an unknown device and it gave me this interval. No idea if that's just a default one.

![screen shot 2017-05-30 at 20 16 10](https://cloud.githubusercontent.com/assets/10297361/26598163/bbeec2e0-4574-11e7-80a3-3602474df4ea.png)

**Comment by caseda** [comment]
then you were lucky to have it in the correct awake state, on the correct time, i have tried 25 times without any succes of even unknown inclusion ;)

**Comment by RobinBol** [comment]
The inclusion bug is fixed but will require a Homey firmware update to work. In the mean time I'll work on the device support.

**Comment by caseda** [comment]
oeh, less work for me 🎉 though its mostly copy paste, only few more parameters

**Comment by Veldkornet** [comment]
Thanks @RobinBol :) Just to confirm the wakup interval, you can check the [Fibaro webstite](http://manuals.fibaro.com/door-window-sensor-2/#post-4859), for this as well as all of the other advanced parameters.

**Wake up interval (battery mode)**
Available settings: 0 or 3600-64800 (in seconds, 1h – 18h)
Default setting: 21600 (6h)

**Comment by caseda** [comment]
we like to get it from the device itself, since some manufacturers like to change it with firmware update :)

**Comment by RobinBol** [comment]
Support is here: https://github.com/athombv/com.fibaro/pull/148, but we'll have to wait for 1.3.0-rc.11 to hit stable before it can be released.

**Comment by Veldkornet** [comment]
So, I have Homey 1.3.1 and Fibaro app 1.5.2, but I still have the exact same problem.
Has the update already been applied in 1.5.2?

**Comment by caseda** [comment]
the support is not in app update 1.5.2, but i guess it will come soon.

**Comment by Veldkornet** [comment]
Right, but the fix for the problem with it hanging during the setup was resolved in Homey 1.3 right?

Although, now it hangs for me during the exchange of security keys, not the wake-up period.

Or is this also somehow affected with the Fibaro app update?

**Comment by caseda** [comment]
no that is not possible, what is the distance from homey

**Comment by Veldkornet** [comment]
~2 meters? I hold it in my hand and stand in front of Homey

I tried twice with the same result

**Comment by caseda** [comment]
2 meters is the max for secure inclusion to successfully include, i would definitely try it closer :)

**Comment by Veldkornet** [comment]
Really? My Fibaro smoke detector is 2 floors above and gets added without problem.

But, I'll wait for support for the device first anyway before I try again

**Comment by caseda** [comment]
there can be a lot of things intervening during inclusion, there is a lot of data transferred from and to a device, but also the location can cause different inverences, like certain glass can absorb 80% of all frequentie that z-wave sends in.
have certain places in my house also where inclusion won't work unless 50 cm away from homey, while 2 meters to the side of that place i can reach 4 meters! and still include properly

**Comment by Veldkornet** [comment]
The Fibaro app updated to 1.5.3 today, and I was able to now add all of the sensors without any problems! 😄 👍

**Comment by RobinBol** [comment]
Great, thanks for letting us know!
