### ISSUE TITLE
Fibaro Universal Binary Sensor FGBS-321- incorrect labeling

### ISSUE THREAD

**Issue by lgaerd** [athombv/com.fibaro#146]
There is a incorrect labeling for temperature sensors 2 to 4 at the fibaro universal sensor. See screenshots...

![fibaro_universalsensor_1](https://cloud.githubusercontent.com/assets/29087006/26620009/4a88987a-45e1-11e7-87c0-a56fa5277cee.JPG)
![fibaro_universalsensor_2](https://cloud.githubusercontent.com/assets/29087006/26620014/51fd9236-45e1-11e7-98aa-0fec086a07a2.JPG)

**Comment by caseda** [comment]
That is not incorrect, if there was temperature values send /connected they won't be shown in insights as there is no data for them. 
Input 1 and input 2 are both separate inputs it also has

**Comment by lgaerd** [comment]
Temperature Sensor 1 right label
Temperatuur Sensor 2 wrong label
Temperatuur Sensor 3 wrong label
Temperatuur Sensor 4 wrong label

**Comment by caseda** [comment]
fix is waiting for approval :+1: thank you for reporting

**Comment by RobinBol** [comment]
Thank guys, fix is merged and will be released shortly!

**Comment by madmax75** [comment]
The incorrect translation is fixed now in FGBS-001.json. 
![fgbs-001](https://user-images.githubusercontent.com/29087006/26973602-8f62ca6e-4d17-11e7-8887-d36b9e58cacc.JPG)
But how do I get the correct translation in insights?
![fgbs-001_insights](https://user-images.githubusercontent.com/29087006/26973674-dd9b0cd2-4d17-11e7-8b8c-708fb18e2dd3.JPG)

**Comment by caseda** [comment]
I thought it would update automatically along side the capability title..  But I guess it is saved on first data entry, if you delete it from insights (see the three dots), and then when the first data comes in it will get the new name.

**Comment by madmax75** [comment]
@caseda 
I've tried it. But nothing changes

**Comment by caseda** [comment]
Then you probably need to re include it

**Comment by madmax75** [comment]
Oh no ...

**Comment by madmax75** [comment]
i have to re include it and now it's ok
