### ISSUE TITLE
FGKF-601 Keyfob multiple keypress trigger not working

### ISSUE THREAD

**Issue by jaimevisser** [athombv/com.fibaro#149]
Homey 1.3.0-rc11
Fibaro 1.5.0

Wanted to use single/double/triple keypress to trigger ventilation setting (off/normal/fast). Not able to trigger flows with the double/triple keypress.

**Steps to reproduce**
Add a keyfob to homey.
In device settings, enable triple press for all buttons.
Save setting, wake up device.
Create 3 flows for triggers with single/double/triple keypress, let homey speak out the number of keypresses (1, 2, 3).

**Expected**
Single press, homey says "One". Double press, homey says "two". Triple press, homey says "three"

**Actual**
"One", "OneOne", "OneOneOne". (Beatboxing homey)

I expect the setting is not correctly saved to the Keyfob.

**Comment by caseda** [comment]
did you activate it in the settings?

**Comment by caseda** [comment]
how do you wake up the keyfob, the way the manual shows, or the way that is written in the readme

**Comment by jaimevisser** [comment]
Ah, will try that sequence! Athom should allow app developers to add extra hints after saving settings for battery powered devices.

**Comment by jaimevisser** [comment]
Yeah, works!
