### ISSUE TITLE
[Device Settings] Roller Shutters

### ISSUE THREAD

**Issue by madmax75** [athombv/com.fibaro#151]
Why are this devices only support some settings:

_Supported devices with some parameters:
FGR-221, Roller Shutter
FGRM-222, Roller Shutter 2
FGR-222, Roller Shutter 2 (v2.5)_

**Comment by caseda** [comment]
Ah, that's a reminance when it was not possible yet to set the position with percentage, which is possible now.

**Comment by madmax75** [comment]
Ok, thanks for the information

**Comment by RobinBol** [comment]
Most parameters are indeed included, venetian blind support is something we might add in the future.
