### ISSUE TITLE
FGS-223 ZW5 v3.2 Fibaro double switch 2 does not pair

### ISSUE THREAD

**Issue by HarryHobma** [athombv/com.fibaro#153]
The Fibaro double switch 2 is unable to pair with homey.
I reboot homey.
I reset the switch push button B until yellow and push 3 times until reset blinking red.
I.e my 3 times pushing the button is in the right pace.
disconnect switch from the power.
Connect switch to the power.
put homey in pairing mode Fibaro > Dubbele schakelaar 2 and the double switch within 50 cm from homey.
push 3 times button B light out at start and on at the end.
get time out from homey and no successful pairing.

Please advise how to follow-up and is this an issue of the app, the homey or interference from a fridge or so?

Using homey 1.3.1 
and fibaro 1.5.1

**Comment by chrisboer** [comment]
Try pressing the reset button (B) and keep it pressed in while putting power on the device. 
It will be reset completely.

**Comment by HarryHobma** [comment]
thanks for the reply. Although it did not work out. 
I get the red blinking light (one time) after keeping pressing the reset button(B).
Also when i power on the device i see one red blinking light at first.
pairing still does not work with homey and a time out is given in the end on the homey screen.

Is it an issue with homey or the app?
used  fibaro 1.5.2

**Comment by caseda** [comment]
Red = can't connect to the controller it is paired with (can be homey if it failed on one of the steps).

So you will have to reset your switch, either via homey's setting > zwave > remove device then activate the learning mode by pressing the b button 3 times, or by switching 3 times with the switch attached to S1.
Or the way @chrisbroer is describing.

**Comment by HarryHobma** [comment]
Somehow the unit is not responsive into homey actually two devices. One is already mounted in the wall and the other one is setup for practice next to the homey.
In the mean time i disconnected and reconnected a FGMS-001, Motion Sensor ZW5 V3.2 without any issues.
Two FGS-222 double switch and two wall plugs have been previously successfully paired although with different versions (homey/Fibaro app). These just do not like to go. ;(

**Comment by caseda** [comment]
I have noticed with my Fgs 22ě that the b button not always works properly, so I do hope you also tried the switch attached to s1

**Comment by HarryHobma** [comment]
I did try this also and i have a light attached so i know that the light(switch s1=off) is out when initiating pairing.

**Comment by caseda** [comment]
Also the resetting of the device?
You need to get the confirmation that the device was deleted/reset properly from homey.

If even that is not working then something is wrong with your switch itself.

**Comment by HarryHobma** [comment]
Found a way to finally connect.
Which made homey react and pair!!
While trying out various modes i found that when i had the unit in unpaired "disconnection" mode.
That did work as follows:
go through the menu through led indication until yellow This is to reset the device but after entering this mode and pushing three times for resetting the inclusion started and worked both switches are recognised.
I do not know if this is the procedure but it worked !!

**Comment by caseda** [comment]
i didn't even know the LED could go yellow, and is also not mentioned in the manual, how did you receive/know of this procedure?
sounds more like a different device's reset (like the wall plug)

though that means this fixed now i guess?

**Comment by HarryHobma** [comment]
[FGS-2x3-EN-T-v1.1.pdf](https://github.com/athombv/com.fibaro/files/1075481/FGS-2x3-EN-T-v1.1.pdf)
Some how i managed to fix it. See attached the manual as reference.
Both switches are working, including kW.
I will get one more unit installed and will see if i have the same issues and if i can replicate the pairing/inclusion method.
The best is to make a dummy set-up and pair before installing into the wall.

**Comment by caseda** [comment]
did you manage to include the later unit?

if so we can close the issue 😃

**Comment by HarryHobma** [comment]
The second unit i have been able to pair just three clicks and it worked. What i found out that i  might be too slow with clicking three times. it must be faster than that the switch switches (read: click).
The issue can be closed.

Both switches are in use one as virtual switch for downstairs lighting.
the other i want to use as an indication if some one stands outside at night by checking the power to the outdoor lighting which is switched by a motion sensor.
The threshold can give a trigger.

Fibaro version 1.5.3
Homey 1.3.2

**Comment by RobinBol** [comment]
Since it seems this issue is resolved for you I will close it, if you ever happen to have issues again, please open a new issue!
