### ISSUE TITLE
FGD-212, Dimmer 2 calibration quirck

### ISSUE THREAD

**Issue by goyaweb** [athombv/com.fibaro#154]
I've got a 9W Philips LED bulb connected to the Dimmer 2. When operating it with a "tuimelschakelaar" switch the light goes on  for a second and then auto turns of. This started happening after performing an auto-calibration WITHOUT bypass.
It started working again as expected when doing an auto-calibration WITH bypass even though no bypass is installed.

**Comment by caseda** [comment]
It is working as the manual tells us,and you are the first of many with this behavior, so not a thing we can do anything about...

**Comment by goyaweb** [comment]
somebody's got to be the first...

**Comment by caseda** [comment]
Yup, but also a thing that we won't/can't change just because 1 someone has the "issue", 9w led is usually not even working without a bypass,
way too low

**Comment by RobinBol** [comment]
This is not a Homey related issue, will therefore close it
