### ISSUE TITLE
Dimmer Triple-click triggers flow several times

### ISSUE THREAD

**Issue by magind** [athombv/com.fibaro#158]
Dimmer 1,
Trigger: Dimmer scene: Pressed left 3x.
Result: Flow is triggered from 2-4 times. 

It appeared to work as intended the first days, but then it suddenly started to respond several times to one trigger. 
I'm not sure this is an issue with the Fibaro-program or the Homey-software, but I'm reporting it here to begin with.

**Comment by RobinBol** [comment]
Hi, what Flow card is triggered 2-4 times? The 'Dimmer scene: Pressed left 1x'. or 'Dimmer scene: Pressed left 3x'? Could you append a Z-Wave log (Settings > Z-Wave > Stuff for geeks) after you have reproduced the issue?

**Comment by magind** [comment]
It was the "pressed left 3x (momentary)" that was triggered up to four times. It suddenly worked again when I reactivated the scene a month or two ago. So I'm not able to reproduce anymore. I think this issue can be closed it there's no objection.

**Comment by RobinBol** [comment]
Ok thanks for letting us know, if the issue resurfaces let us know!
