### ISSUE TITLE
Battery of Keyfob drains in 4 day's

### ISSUE THREAD

**Issue by SanderVlotman** [athombv/com.fibaro#159]
Just added two Fibaro Keyfob 2 day's ago and now the battery is allready on 50% only while i'm not using it very often. The otherone was just added today and is now 80%. I googled if something is wrong with the device but fibaro and smartthings users do not report about this issue. Maybe the Homey app is comunicating to heavy? Please let me know if I can help in analyzing by sending logs or someting (I'm not a programmer). 

I'm using the other devices from Fibaro app with success. Thanks!

**Comment by RobinBol** [comment]
Hi Sander, I think I already answered your support request about this if I am correct. Shall we continue the discussion there?
