### ISSUE TITLE
Missing parameter in FGMS-001 settings

### ISSUE THREAD

**Issue by nicoroosenboom** [athombv/com.fibaro#16]
Although the FGMS-001 is not working yet with Fibaro App v1.0.4, I also found a missing parameter when changing the 'Led Signaling Mode'. Parameter "6" (Blue) is missing in the drop-down menu.

<img width="609" alt="screen" src="https://cloud.githubusercontent.com/assets/20779697/17306251/458d9fa0-582f-11e6-8201-1e0650cfcf2a.png">

**Comment by ralfvd** [comment]
@WeeJeWel I've fixed this in my code, pull request 18

**Comment by nicoroosenboom** [comment]
Thanks Ralf, I see parameter 6 available now in update 1.0.5.  There's still a cosmetic bug, parameter 6 is not 'Green' but 'Blue'.

![screen](https://cloud.githubusercontent.com/assets/20779697/17357648/289513bc-595e-11e6-8701-ac0e01209108.png)

**Comment by ralfvd** [comment]
Solved in 1.0.5 ; can you check ? And if it is solved, please close the issue ticket. Thanks!
