### ISSUE TITLE
FGMS ZW5: day and night reversed

### ISSUE THREAD

**Issue by nlrb** [athombv/com.fibaro#162]
The setting on the Fibaro ZW5 motion sensor is reversed for day and night (checked Dutch only).
Set lux threshold to e.g. 10.
Set to trigger 'Snachts' only - there will be no trigger, even if it is dark.

**Comment by caseda** [comment]
it's just like the manual tells us:
http://manuals.fibaro.com/content/manuals/en/FGMS-001/FGMS-001-EN-T-v2.1.pdf

> 8. Motion detection - operating mode
> This parameter determines in which part of day the PIR sensor will be
> active.
> This parameter influences only the motion reports and associations.
> Tamper, light intensity and temperature measurements will be still
> active, regardless of this parameter settings.
> Available settings:
> 0 - PIR sensor always active
> 1 - PIR sensor active during the day only
> 2 - PIR sensor active during the night only

so might be something completely different

**Comment by nlrb** [comment]
Ok, I see the code is indeed inline with the manual. Let me do some more testing to see if I can figure out the issue. Thanks for the quick response and sorry to jump to conclusions.
