### ISSUE TITLE
Fibaro dimmer 2 not responding

### ISSUE THREAD

**Issue by jeroenvano** [athombv/com.fibaro#164]
All my Fibaro dimmer 2 devices are dis responsive after a couple (6+) of hours. Rebooting Homey does resolve the issue. I have multiple zwave devices from different brands but only all my dimmer 2 devices have this issue.

**Comment by RobinBol** [comment]
What Homey firmware are you using? Is this still happening?

**Comment by jeroenvano** [comment]
I am on current stable 1.5.1 and had experienced it once running this
version. Only PTP solves the problem to restore full dimmer 2
functionality.

It happens after a few days running. Also lost connection to FMS plus unit
that is no longer recognized as a paired unit. Remove and add new is only
solution for the FMS.

Let me know what you need to investigate

Jeroen

Op 25 sep. 2017 18:51 schreef "Robin Bolscher" <notifications@github.com>:

**Comment by jeroenvano** [comment]
Today again 4x fibaro dimmer 2 did not respond. So still an issue on
current stable version.

Op 26 sep. 2017 14:55 schreef "Jeroen van Oosterhout" <joosterhout@gmail.com

**Comment by jeroenvano** [comment]
I am having daily issues now again with 4x fibaro dimmer 2 that are not
responding on homey. PTP only resolves for a few hours or less.

Let me know if you need more information as I would like to see this
restored/fixed as it becomes kind of irritating now ;)

With kind regards
Jeroen van Oosterhout

Op 27 sep. 2017 21:03 schreef "Jeroen van Oosterhout" <joosterhout@gmail.com

**Comment by ArchiSpec** [comment]
Same issue here. Installation of 40+ units (qubino & fibaro mainly). All fibaro units stop working at sporadic intervals - anything from 10 minutes to several hours. Soft restart of homey sorts it for a few minutes, PTP solves for longer. But all fibaro dimmer 2 units stop working, plus one double relay plus (but another one, keeps working strangely - the ONLY fibaro unit which does keep working)!!!

**Comment by RobinBol** [comment]
Thanks for reporting, I have made an issue here https://github.com/athombv/homey/issues/1899 to summarize your problems (reported multiple times). The discussion will continue there, so I will close this issue.
