### ISSUE TITLE
Z-Wave chip crashes /w parameter changes

### ISSUE THREAD

**Issue by caseda** [athombv/com.fibaro#17]
App: 1.0.4 (was with .3 also)
When you change any parameter to anything above 40-45 will crash the Z-Wave chip. (like the intervals)
- Grayed out settings buttons
- "WAIT" status, stays active
- Parameters don't get send to the sensor.

Only testing with 1 motion sensor (rest is still not paired)
Don't get any error message in console or on the sensor.
After a power cycle i can remove the device (a short amount of time), after deletion i need to power cycle again because of Z-Wave chip crash (sometimes it recovers on its own after 30-60 seconds).
After power cycle it is working again properly.

Configuring up and down, noticed that when going to 45 (instant crash) power cycle and change back to 40, it wil keep working (tested with illumination treshold)

maybe has something to do with #15 ?

**Comment by WeeJeWel** [comment]
Is this still the case with 1.0.6?

**Comment by caseda** [comment]
After some trouble to even get any parameters to save to the sensor (only after a z-wave reset and power cycle afterwards) It wont crash anymore.

But, it doesn't save the "Led Indicating Tamper Alarm" anymore, maybe thanks to the latest Boolean change?
And battery doesn't show anymore (either a dash (null) or a 0% after a sensor wake-up)

Also noticed:
After a power cycle, the sensor needs to wake up as well to get anything on the device card or even trigger the motion alarm

**Comment by robertraaijmakers** [comment]
Maybe this has something to do with this issue: https://github.com/athombv/node-homey-zwavedriver/issues/2 ?

**Comment by caseda** [comment]
@robertraaijmakers
Original (top) issue was fixed.
But it's not really the exact same issue, my values were not out of bound.
My one was more, a not proper integer value bug.

The out of bound bug should be fixed as well though.

**Comment by caseda** [comment]
Found the "led indicating tamper alarm" not saving.

fixed the cause (flipped parser) in my pull request
