### ISSUE TITLE
No battery status after reboot

### ISSUE THREAD

**Issue by StraDijk** [athombv/com.fibaro#170]
Not working:
Fibaro Door/Windows Sensor 1 (plus and non plus)
Working:
Fibaro motion sensor

What is your Homey version (Settings → System)?
1.5.3

What did you try to achieve?
No battery status after reboot

Please include detailed steps how we can reproduce the issue
Reboot Homey

What was the result?
No battery status. 

What did you expect as result?
That the battery status will be updated after reboot

Any other remarks
Only manual wakeup solves this.

Please attach a Homey System log (Settings -> System -> Send Log)

**Comment by CyberSponk** [comment]
What for an Fibaro-Device? Or all Fibaro-Battery-Devices?

**Comment by StraDijk** [comment]
Good one. added!

**Comment by Veldkornet** [comment]
I have the same issue, usually if I pull and re-add the battery, the status comes back.

Is it possible that it's because the battery status just hardly ever changes and thus never sends an update?

**Comment by RobinBol** [comment]
That is a known Fibaro issue, the devices usually don't respond to a `BATTERY_GET` request by Homey. Waking them up usually solves it temporarily.

**Comment by RobinBol** [comment]
Create an issue with some more information here: https://github.com/athombv/homey/issues/1898, will close this one to prevent duplicates.
