### ISSUE TITLE
FIBARO RGBW does not change the dimming state at power-on

### ISSUE THREAD

**Issue by Korenets** [athombv/com.fibaro#171]
FIBARO RGBW Controller FGRGBWM-441 

If the RGBW is turned on, the dimming scale does not automatically change its state

**Comment by RobinBol** [comment]
@caseda something you want to take a look at?

**Comment by caseda** [comment]
I'll look into it, probably already know what's up, and how to fix it

**Comment by RobinBol** [comment]
@caseda do you perhaps have an update? Or is it something I have to look into? Thanks!

**Comment by caseda** [comment]
will send in the fix this evening

**Comment by caseda** [comment]
Hmm, seems the issue is a bit more weird/stubborn (but then again debugging with 5 modules sending debug info doesn't make it really easy), so will continue fixing this evening.

**Comment by RobinBol** [comment]
@Korenets this issue should be solved by now (via caseda's PR), so I'll close this issue for now. If it was not solved please let us know!
