### ISSUE TITLE
Fibaro Smoke Sensor (FGSS-001) Pairing Issues?

### ISSUE THREAD

**Issue by lesterchan** [athombv/com.fibaro#173]
Not sure if I am the only one experiencing this issue.

I could not pair my Fibaro Smoke Sensor (FGSS-001). I tried for more than 10 times. Even did a factory reset of the sensor

When pairing, it will go from Node Found -> Node Identified -> Could not reach the device anymore. And the best part is that I did not even move the pairing device!

![36551868324_35b500bf13_o](https://user-images.githubusercontent.com/355829/31051873-a80b5264-a6a6-11e7-9e2f-0e68e58b77ae.png)

I have about 55 z-wave devices, so not sure is it because of congestion. But after I failed to pair the sensor, I paired a powered TKB Metered Switch and it paired fine.

**Comment by RobinBol** [comment]
Hi! Battery devices are more prone to failing inclusion when the pairing process is disturbed by a lot of other Z-Wave traffic. You could try to lower traffic on your network by changing some reporting settings on your devices. Or temporarily take them out when pairing. Also, make sure the sensor is really really close to Homey during pairing (max 30cm in such a congested network). Please let me know if you manage to pair the device, then I'll close this issue. I don't think there is really a bug in Homey of some sort.

**Comment by lesterchan** [comment]
I see thanks. I tried many times but still could not get it to pair. You can close this =)
