### ISSUE TITLE
Fibaro Switch 2 stopps reacting

### ISSUE THREAD

**Issue by Andi1927** [athombv/com.fibaro#174]
I have three Fibaro Switches Two FSG-213 and one FSG223. I always have the issue that after 16-40hours the switches are no more reacting. Means either from Flow and also not from the direct Userinteface. Cant switch them on/off. I have Homey 1.5.3 and the newest Fibaro App 1.5.9.
If I reboot Homey everything start to working again. I tried to restart only the Fibaro app this doesn´t help. The devices are only 4m away from homey. And always all 3 are no more working. I came from Devolo before and the same devices doesn´t have this issues before. Any Idea ?
Last but not least I tried to RESEZ ZWAVE and reinclude all zwave devices but the issue is still the same. With the other devices from Devolo and Fibaro Motion sensors I have no issues.
I posted this in the Forum and there were two users which had the same Problem.
https://forum.athom.com/discussion/comment/60042#Comment_60042

kind regards
Andreas

**Comment by Veldkornet** [comment]
I have the same issue with one of my Fibaro Wall Plug 2, probably only around once a month or so though.

**Comment by ArchiSpec** [comment]
Same issue here. Installation of 40+ units (qubino & fibaro mainly). All fibaro units stop working at sporadic intervals - anything from 10 minutes to several hours. Soft restart of homey sorts it for a few minutes, PTP solves for longer. But all fibaro dimmer 2 units stop working, plus one double relay plus (but another one, keeps working strangely - the ONLY fibaro unit which does keep working)!!! #

**Comment by RobinBol** [comment]
Thanks for reporting, I have made an issue here https://github.com/athombv/homey/issues/1899 to summarize your problems (reported multiple times). The discussion will continue there, so I will close this issue.
