### ISSUE TITLE
Smoke Sensor V2 (FGSD-002-ZW5) Stops Working After A While

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.fibaro#177]
I have a few Smoke Sensor V2’s (FGSD-002-ZW5) and I’m having a problem where after a while, the devices stop reporting. Only way to fix it is to pull the battery and add it back. 

Although, even when they do “work”, the status of the various sensors are hardly ever shown. 
- Battery (50/50, on some devices it shows, some it doesn’t)
- Smoke alarm (always shows nothing)
- Heat alarm(always shows nothing)
- Temperature Sensor (this is about the only thing which does show, which is how I know when it stops working). 

![b8c17e16-c6a5-4b01-b5a3-414551292f94](https://user-images.githubusercontent.com/10297361/31400439-e4f8c530-adef-11e7-840a-d2d611bf1035.jpeg)

**Comment by CyberSponk** [comment]
Take a look here: https://forum.athom.com/discussion/1921/fibaro-fgsd-002-smoke-sensor. First Post 09 July from Caseda. Think this will answer your Issue.

**Comment by Veldkornet** [comment]
Okay, I'll keep an eye on it.
