### ISSUE TITLE
No temperatures after Homey reboot

### ISSUE THREAD

**Issue by Veldkornet** [athombv/com.fibaro#178]
I have noted the following after doing a Homey reboot today that the temperature for a number of devices is not reported. Maybe something similar to the batter not showing after reboot? I have two of each device model below:

Devices that do show temperature status after reboot:
- Door Window Sensor 2 (FGDW-002)

Devices that don't show temperature status after reboot:
- Door Window Sensor 2 (FGK-10x)
- Smoke Detector 2 (FGSD-002)
- Multi-Sensor (FGMS-001-PLUS)

For the multi-sensor, it does show and report the other items, such as motion and lx.

**Comment by caseda** [comment]
It can happen after reboot, all values older then 30 minutes will not be used anymore, and getting information from a device that is asleep is _impossible_ until it wakes up or reports on its own

**Comment by Veldkornet** [comment]
I see, so basically I'm impatient ;)

Why then does the Door Window Sensor 2 show though? Or is it just coincidence that this model is showing the temps? They seem to have the same settings.

Door Window Sensor 2:
![door](https://user-images.githubusercontent.com/10297361/31440839-982e8134-ae91-11e7-8b32-41e057a860a0.PNG)

Multi-sensor:
![multi](https://user-images.githubusercontent.com/10297361/31440847-9f1c447c-ae91-11e7-954e-67efed138e9e.PNG)

**Comment by caseda** [comment]
Value must have been less then 30 minutes old

**Comment by Veldkornet** [comment]
Hmm, okay, I'll keep an eye on it and report back if needed.
