### ISSUE TITLE
Fibaro RGWB labeled as "Invalid Node"

### ISSUE THREAD

**Issue by cbho** [athombv/com.fibaro#182]
Hi,
for some reason my Fibaro RGBW Controller (FGRGBWM-441) has been labeled as "Invalid node".
There's no obvious reason why something should have changed hardware-wise.
The controller can be turned on/off/dimmed via direct association - therefore I suspect it is a software-issue.

Have tried ex-/include several times, which is possible without any problems.
Initially, settings for the controller are available, but within a short while, Homey labels it as "Invalid Node".
Homey has of course been rebooted as well.

Homey Firmware v. 1.5.3
Fibaro App v1.5.12

**Comment by RobinBol** [comment]
Can you confirm that if you include the device (and do not change settings), the device keeps on working?

**Comment by cbho** [comment]
After rebooting Homey a couple of times for other reasons, the node now appears normal again - will close issue for now.
