### ISSUE TITLE
Support for new Thermostat Valve 

### ISSUE THREAD

**Issue by mruiter** [athombv/com.fibaro#187]
Please add support for the new Fibaro Thermostat Valve and its bluetooth (tru z-wave) external temperatuur sensor.

https://www.fibaro.com/en/products/the-heat-controller/

**Comment by synegic** [comment]
This would be great! I also have two of these now and am eager to set them up with Homey.

**Comment by synegic** [comment]
Started on this already.. It works, but that's about it. Here are some initial findings;

- It is designed to be used with a schedule (overrides are temporary), this may pose some challenges getting it fit for use with Homey as I wouldn't know how we would implement this other than in the settings pane for device or app.
- It supports controlling by override, by default this setpoint change lasts 240 minutes. You could higher this to get a manually controlled valve and dealing with everything through flows, of course.
- You cannot read out the temperature it measures with the internal temperature sensor. It only supports measuring temps from the external (bluetooth) sensor.
- Get battery level does not seem to give back anything useful.

You may find/review my initial support hack here; https://github.com/synegic/com.fibaro/commit/21d5684e787a335d8bafa5d48e4d8ee8b3cc2d55

**Comment by mruiter** [comment]
I have not seen the schedule change the setpoint set by Homey.
I'm running the valves on SDKv2 . When i set a setpoint it stays there until a next setpoint is given.
As far as i can see the 240 min setpoint last only lasts when you upload a active schedule to the valves.
Pairing to Homey does not do this so the setpoints are perminent.

I only have seen a battery value pass once in my debug testing on SDKv2 version.
Dont know but maybee they only report when battery becomes low.
I have them now running for 4 weeks and still no sign of a low battery so i cant tell yet.

**Comment by synegic** [comment]
Ok, that's very good news. I really don't think an internal schedule is needed if you'd make use of flows or the Heating Schedule app (which isn't SDKv2 as far as I can tell - so no idea how long that'd last).

I'll be creating some flows later this week, and see how it goes. :-)
