### ISSUE TITLE
Support for a new FIBARO Wall Plug EU WiFi/BLE

### ISSUE THREAD

**Issue by anarro** [athombv/com.fibaro#188]
Please add support for the new Fibaro Wall Plug EU WiFi/BLE (with HomeKit support)

**Comment by MatthewWaanders** [comment]
Hi @anarro!

Could you provide us with a product model number?

**Comment by RobinBol** [comment]
Thanks for reporting. The Fibaro app currently supports all Z-Wave Fibaro Wall Plugs, we don't have plans to add support for the Wifi/BLE version. If you want the plug to work with Homey you need the Z-Wave version.
