### ISSUE TITLE
Smoke sensor times out

### ISSUE THREAD

**Issue by Rubelke** [athombv/com.fibaro#19]
The setup takes to long
Adding the smoke sensor ends with a error because of the association group timeout.
This happens with the new 1.04 software.

**Comment by robertraaijmakers** [comment]
Same here, sometimes reboot helps, but most often you need to reset your whole z-wave network and re-add the devices from scratch and then it works. Strange bug though.

**Comment by Rubelke** [comment]
Problem seems to be solved by version 1.05 software
Sensor installed without any problem
