### ISSUE TITLE
FGWPx-102 Wallplug not triggering flows and unable to control LED-ring from flow

### ISSUE THREAD

**Issue by bm480** [athombv/com.fibaro#197]
I'm using Homey v1.5.6rc7 (coming from v1.5.5). I have a few flows that monitor the power consumption of a waterboiler connected to the wallplug and change the color of the LED-ring depending on the state of the boiling process. I noticed that since a few days (not sure if it is caused by the Homey update itself) changes in the power consumption do not trigger flows anymore. However, I can still read the exact power consumption in the device settings. Also, when manually triggering the flow the action that changes the LED-ring color doesn't have any effect.

**Comment by chrisboer** [comment]
I have the same issue with v1.5.6 rc8

**Comment by bm480** [comment]
This may be related to #204 and #202.

**Comment by caseda** [comment]
Unrelated to 202

**Comment by RobinBol** [comment]
@bm480 can you confirm that this issue is still present? If so, what Homey firmware version are you using at the moment?

**Comment by RobinBol** [comment]
Closing since the reporter seems to have abandoned this issue. If you find this issue closed at a later moment in time and the issue persists, please let us know.
