### ISSUE TITLE
Tamper Alarm is missing

### ISSUE THREAD

**Issue by philsniff** [athombv/com.fibaro#2]
In 0.8.38 there was beside motion alarm, lumination, and temperature a fourth: tamper Alarm

**Comment by Inversion-NL** [comment]
For which device?
Because I'm also missing this for the v1 smoke sensor

**Comment by philsniff** [comment]
For the motion sensor zwave plus

**Comment by caseda** [comment]
All devices that are now in the fibaro app have no tamper alarm.
the entire capability is not used (maybe not even written?) in the app.

**Comment by 2benl** [comment]
For the motion sensor there's a pull request from ralfvd who added this to the app.

**Comment by WeeJeWel** [comment]
Added tamper alarm to Motion Sensor (also Plus), any others missing?

**Comment by 2benl** [comment]
Luminance is also missing

**Comment by WeeJeWel** [comment]
@2benl I'm pretty sure it isn't?

**Comment by caseda** [comment]
Luminescence is indeed there.
The door sensor(s) are missing the measure_temperature still.
And the wall socket is missing its meter_power capability, tried to add this myself but only got to an error that the value wasn't correct.

**Comment by 2benl** [comment]
Maybe it is because off the fact that I have a zwave plus motion sensor. I don't recieve any reports except for the communication when the device is added

**Comment by caseda** [comment]
@2benl until the version @WeeJeWel is busy with, add the id of homey (1 mosy likely) to association group 1, this will give temperature and luminescence

**Comment by caseda** [comment]
BTW @WeeJeWel did you change/add homey's id to association group 1 for all z-wave+(plus) devices?
