### ISSUE TITLE
Motion sensor Z-wave plus (FGMS-001) temperature offset description not correct

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/com.fibaro#201]
In the settings of the Motion sensor Z-wave plus (FGMS-001) you can set a temperature offset. However, Homey states that the temperature offset is in °C (with a range of -100 till 100).  But I believe this temperature offset is in steps of 0.1°C. I wrote down -6 and I believe my temperature reading has changed with -0.6°C instead of -6°C.

The manual of the Fibaro motion sensor states: 
![image](https://user-images.githubusercontent.com/17165733/35210440-82c5c8c2-ff52-11e7-84d3-5ccbd2240a55.png)

Perhaps you need to add an description to this setting that the number is multiplied with 0.1°C.

We need to set the temperature offset in step of 0.1°C since steps of 1°C are too big.

**Comment by RobinBol** [comment]
The value you enter is multiplied by 10, since the Homey setting gives a range of -100 to +100. So if you enter -6, the value send to the device is -60. You could also have entered -6.3 if you need the 0.1°C steps. Does this answer your question?

**Comment by JesperJanssen** [comment]
I see now that the values are multiplied by 10 by Homey. Maybe change the description of the range to -100.0 to +100.0.  I did saw the option of adding a decimal in the beginning either.

Fuethermore, I believe the wake up time is not working for the motion sensor. This got me also confused
