### ISSUE TITLE
Fibaro Double Switch 2 not reporting power for secondary output.

### ISSUE THREAD

**Issue by JohanBendz** [athombv/com.fibaro#203]
The Fibaro Double Switch 2 show Power Meter information för both outputs but only Power for the first output.

**Comment by RobinBol** [comment]
@MatthewWaanders could you check if this is still an issue in the SDKv2 rewrite?

**Comment by MatthewWaanders** [comment]
Closed in favour of issue #259 which is the same issue, on a newer release
