### ISSUE TITLE
Fibaro flood sensor

### ISSUE THREAD

**Issue by gajdur** [athombv/com.fibaro#21]
Fibaro flood sensor is only working in battery mode.

If connected with DC and then paired is going to crash the fibaro app (1.0.4). Removing is impossible, app is crashed, all devices are gone.

Workaround to not remove everything: disable the fibaro app, then reinstall it. Device is still here but not removable. I created Device folder with ghost devices and moved all failed sensors here.

**Comment by denniedegroot** [comment]
I have a similar issue when connected with a DC power supply. With the Fibaro 1.0.6 app the device is pairing but gives an error when trying to show the device data. It shows the following error:  "invalid_commandClass_COMMAND_CLASS_BATTERY".

**Comment by caseda** [comment]
athom should implement that when:
"battery" = false
ignore measure battery capability.

It can't be done in the code of the driver unfortunately.

**Comment by RobinBol** [comment]
Created generic issue as this is not only applicable to the Fibaro app: https://github.com/athombv/homey/issues/858
