### ISSUE TITLE
Fibaro universal binary sensor

### ISSUE THREAD

**Issue by tranceblast** [athombv/com.fibaro#216]
I have very bad problems with fibaro in Fw 1.5.8 which I did not have in 1.5.3. For example, fibaro door/window sensor that usually doesn't send "opened" or "closed" when I open and close a door. Or my 3 fibaro binary sensor that usually does not send "opened" or "closed" from inputs.
I have tried to remove the devices and add them again with the same results.

**Comment by Arjanvde** [comment]
#198

**Comment by MatthewWaanders** [comment]
As @Arjanvde pointed out, this is probably part of issue #198, as such I'm closing this issue.
