### ISSUE TITLE
RGBW set "night light" OFF

### ISSUE THREAD

**Issue by eelco2k** [athombv/com.fibaro#221]
In the flow editor you can set: Night Light "ON" but there is no option to set Night Light "OFF" the set Light off doesn't work as expected unfortunately.

**Comment by caseda** [comment]
Not sure where you see that, as there is no "night light" option in the rgbw controller

**Comment by eelco2k** [comment]
sorry posted it to the wrong app.... had to post it to the mi-light app issue board.
