### ISSUE TITLE
RGBW Controller - No possibility for setting parameters

### ISSUE THREAD

**Issue by mbrouw** [athombv/com.fibaro#24]
In the settings popup only the Association groups are shown and changeable. I want to be able to set the different parameters.

**Comment by Inversion-NL** [comment]
In the next Homey firmware update your able to set custom parameters for every Z-Wave device, I've read on Slack today

**Comment by caseda** [comment]
I my pull request i have added some of the parameters for the RGBW controller.

If one (or two) aren't present feel free to ask and i will add them (if possible)

**Comment by RobinBol** [comment]
Device settings are implemented for the RGBW controller in the latest version.
