### ISSUE TITLE
Fibaro FGRGBWM-441, RGBW Controller; pre-programmed mood settings unavailable

### ISSUE THREAD

**Issue by Gorlimtouk** [athombv/com.fibaro#257]
As you may know, the fibaro rgbw has animation build into the controller
the id value 0, 1, 2 3, 4 are available for Fibaro HC2 (to make own animation program with fade & timing)
this will take some time if you'd add it to homey.

More interesting (quick gain!) is the availability of the pre programmed Animations

From (source: http://forum.micasaverde.com/index.php?topic=37989.0) for Luaa
"You select the RGB Controller plug-in device in your scene, in my case device ID 139. Not the actual Fibaro RGBW device. 
And use the option "StartAnimationProgram". 
And use the animation names and ID numbers as shown in my list:
RGBW - Fireplace 
 { programId="6" }
 
RGBW - Storm
 { programId="7" }
 
RGBW - Rainbow
{ programId="8" }
 
RGBW - Aurora
 { programId="9" }
 
RGBW - LAPD 
 { programId="10" }

i hope that simply adding 5 buttons / 6 option slider (including rgbw preset) will be an easy enhancement!

Some coding on howto get it to work (domoticz based)
Here is a simple way to set the animation:

// 6 = Fireplace
http://localhost:8080/json.htm?type=com ... 2_Ng%3D%3D
// 7 = Storm
http://localhost:8080/json.htm?type=com ... 2_Nw%3D%3D
// 8 = Rainbow
http://localhost:8080/json.htm?type=com ... 2_OA%3D%3D
// 9 = Aurora
http://localhost:8080/json.htm?type=com ... 2_OQ%3D%3D
// 10 = LPD
http://localhost:8080/json.htm?type=com ... =72_MTA%3D

Replace localhost and 8080 with your Domoticz/controlers web server values. Replace idx with the Node Id of the Fibaro RGBW module. 

The cryptic string following the configuration parameter number (72), is simply the number 6-10, base64 encoded and URL encoded. For example from Developer tools console in browser type:

> encodeURIComponent(btoa(8))
"OA%3D%3D"

To switch the animation program off you can use the following URL:
http://localhost:8080/json.htm?type=c ... tchcmd=Off
Change the IDX to the IDX of the RGBW switch in your installation.
I hope this will help as a head start to include it.

PS. aside from a slider (why not color circle/square?) it 'd be nice to just enter RGBW values
(R 0-256 , G0-256 B0-256 W 0-100 K(warmth)

Thanks for reading all the way, and happy coding!

**Comment by caseda** [comment]
you mean the animation flow card is not real? (as in, the default 6-10 animation are already implemented into a flow card :wink:)
The current GUI (non preview mobile/v2) is just not build for RGBW and or adding more and more things like those buttons, that is the reason for it not being in the mobile card, but only as flow card, which you of course van couple to a virtual device if you want to toggle it within the app.

**Comment by Gorlimtouk** [comment]
Thank you for your reply

Never found it at being a flow-card!
I'll make some flows  directly to allow its control.

thank you so much for your time and quick feedback!; if possible put the
topic on solved.


Best luck,

Jeroen


Op za 8 sep. 2018 om 01:50 schreef R Mengers <notifications@github.com>:
