### ISSUE TITLE
FGRM-222, Roller Shutter 2 inversion (<v2.4) doesnt work

### ISSUE THREAD

**Issue by viixxiiv** [athombv/com.fibaro#279]
I see the latest update v 2.1.19 fixed the inversion for the newer roller shutters but one of my older module (product ID 4097, product type id 769) still have the same problem with the inversion Not working.

It works only for the newer roller shutter module with product id 4096, product type id 770.

**Comment by bckp** [comment]
Looks like fix is published only for FGR-222, not the FGMR-222 (version 2.4)

**Comment by viixxiiv** [comment]
It worked before they did all these recent updates..

**Comment by bckp** [comment]
It will be fixed in next release I belive, I saw changes in git sources
