### ISSUE TITLE
Add bounds for most `number` settings

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/com.fibaro#28]

**Comment by WeeJeWel** [comment]
<3 if someone from the community would contribute here!

**Comment by Inversion-NL** [comment]
Do you mean 

"attr": {
	            "min": 0,
	            "max": 99
            },

For every driver with numbers taken from the manual/online Z-Wave DB for that specific driver?

**Comment by WeeJeWel** [comment]
Yep @Inversion-NL !

**Comment by RobinBol** [comment]
This is fixed for all number settings!
