### ISSUE TITLE
status dimmer 2 already added

### ISSUE THREAD

**Issue by ghost** [athombv/com.fibaro#287]
# This issue tracker is disabled

Please report issues [here](https://github.com/athombv/homey/issues). This issue tracker will not be monitored.

Thank you for your cooperation!

**Comment by bckp** [comment]
Report issue into read-only project, REALLY????

**Comment by ewognum** [comment]
Get a life, If you don't want to help costumers may be I suggest you get a
real job instead of pissing costumers off.
