### ISSUE TITLE
No motion detection since firmware 0.9.1

### ISSUE THREAD

**Issue by philsniff** [athombv/com.fibaro#3]
Only one First detection (also Seen in the insights) is realised After pairing succesfully. But from then on no motion detection. It only blinks red if you wink with your Hand in Front of it. Insight is also no log for any but the First detection.

**Comment by caseda** [comment]
Is your sensor the motion sensor with Z-Wave+?

**Comment by philsniff** [comment]
yes it is!

**Comment by ThaYoung1** [comment]
Same problem here, also Z-Wave+ version of the FGMS-0001

**Comment by swttt** [comment]
The v1 (non-zwave-plus) works here! So doesn't seem the same bug as in previous firmware, but might have something to do with the driver :+1:

**Comment by 2benl** [comment]
Z-Wave+ over here working neither.

**Comment by swttt** [comment]
You could try the solution posted here: https://github.com/athombv/com.fibaro/issues/7

**Comment by swttt** [comment]
I might have found the error:
In app.json the capability is set as "alarm_contact" and in driver.js it is "alarm_motion"

So app.json needs to be updated to alarm_motion i guess, and it should work.
Can't test it myself, i don't own the plus version :+1:

**Comment by philsniff** [comment]
Oh and i was glad that someone found s solution 

Perhaps neckt try :-)

**Comment by swttt** [comment]
I am really really sorry! :)

What i did found out, the association group should be 1 and is set in the app.json to 3. Did someone tried to change this already?

**Comment by caseda** [comment]
yep #7

**Comment by swttt** [comment]
But changed the value in the UI or in the app.json? (not sure if it makes a difference tho)

**Comment by caseda** [comment]
It shouldn't matter, the id of homey is being added to the group specified in the array. It doesn't do anything more

**Comment by WeeJeWel** [comment]
It's weird, as it seems to be implemented correctly (as it does sometimes work). The Motion Sensor (only the plus) doesn't seem to send the event that often as the old one...

**Comment by 2benl** [comment]
What is not so often? Once every 2 days?

**Comment by philsniff** [comment]
great app update (1.0.4) with all the parameters. and it seems that my motion sensor plays well.
but i don't know why... the motion detection works sometimes (2-6 times) and then stays on alarm. (the whole night!)

i have excludet, reseted device, reseted zwave entwork etc. and then a fresh include: all seems good, and the sensor worked for a while (perhaps 20 minutes) then suddenly tamper and ,motion alarm stayed and didn't stopped.

is this already known? 

bytheway,  since the last app-update the fibaro app is 10 steps forward!

**Comment by gruijter** [comment]
Same problem for me (fw 0.9.2) with the zw+ version. Besides not getting motion detection (ever!), I also do not get the tamper alarm.

**Comment by philsniff** [comment]
Since 1.0.5 i have no Problems with motion detection. But i have round about 6-7 times my sensor excludet, reseted and New imported. 

What you can try: when you have includet your sensor and some (especially motion and/or tamper) arme not working (detection is always on or doesn't work). Go into sensor Settings and without changing something just Click "save Settings". Then triple Click your sensor for waking up. When it shines blue one Short Click and the blue led goes off. 

Then look if now motion or tamper are detected/work. If not try the Same one or two times more. Just Save the Settings and Wake up the device for saving on it. 

I have the feeling that sometimes the Settings with the parameters not going set complete in the device ...

**Comment by RobinBol** [comment]
@philsniff I understand this issue has been fixed for you? (If not, just leave a comment) I have tested with a FGMS-001-PLUS myself, and after a clean install/pair it works perfectly (without changing settings). 

If the others are still experiencing issues, could you first try a reset of your device, then pair (without changing the settings), and observe whether the issue still persists? If this is the case, please create a separate issue for that!

**Comment by philsniff** [comment]
@RobinBol since i had further difficulties (greyed out zwave-settings etc.) with this sensor i disconnect it and wait how the last weeks would change the situation

so i will try to pair (after reseting device) in the later evening when i am at home.
so i have to test. i will inform you ;-)

**Comment by RobinBol** [comment]
@philsniff do you have an update for me?:)

**Comment by philsniff** [comment]
i am very, very sorry @RobinBol but i was very late at home the last days and today also so i could`t test ist anymore.

i hope i can go for a test late this evening. sorry but time is rare.

**Comment by RobinBol** [comment]
I understand, no problem! Just let me know if issues remain.

**Comment by philsniff** [comment]
i will! thank you

**Comment by philsniff** [comment]
hey @RobinBol 
i just teste my motion sensor plus after a few weeks an must say: all works like a charme and how it should! i now will stay connected and will look tomorrow if all is fine.

at the moment no crashes of the zwave network (no greyed out buttons), motion, battery and all other thing are reported in the insights and the motion detection reacts like i always hoped to.

thx so long! 

i will report (hopefully not) if i run into further issues, ok?
great job!
