### ISSUE TITLE
Dimmer 2 - Inclusion times out during group association (v0.9.2, Fibaro app v1.0.6)

### ISSUE THREAD

**Issue by RT744** [athombv/com.fibaro#31]
Dimmer 2 inclusion times out while groups associations are set. Tyring again to include the Dimmer does not work because inclusion actually seems to succeed but the dimmer does not show up anywhere in the Homey user interface. Dimmer had been reset before. Tried two times with same result. 

**update**: Tried again after resetting z-wave network and power cycling, but it still does not work. Inclusion stops at "setting default association groups" followed by "The interview has timed out, No device has been found." It made no difference wether it chose "Dimmer 2" or "Dimmer".

**Comment by caseda** [comment]
I noticed the same when trying to add my "Universal Binary Sensor"
(creating an app-device for it at the moment)

So it seems they are devices implemented by us users.
Because the athom implemented ones are being added properly.
Going to investigate why that is (what's the difference?)

**Comment by caseda** [comment]
After a short investigation (still no clue why) i got my device included..
I did do a power cycle (short one) so maybe that fixed it.

**Comment by hnijveen** [comment]
Same issue here. Cannot include Dimmer 2: time out. Did try caseda's suggestions.

**Comment by RobinBol** [comment]
Do you guys try to include secure?

**Comment by RT744** [comment]
There seems to be no way to choose either secure or non-secure. Moreover I included my dimmer 2 long before v0.9 came out, never cared about secure / non-secure. After v0.9 I had to reset the dimmer because inclusion was not possible without reset. I follow the same steps for inclusion as before, so inclusion should work like before too.

**Comment by RobinBol** [comment]
Created generic issue as this is not only applicable to the Fibaro app: https://github.com/athombv/homey/issues/860
