### ISSUE TITLE
Homey dimmer slider value vs fibaro devices off-by-one issue

### ISSUE THREAD

**Issue by bkockx** [athombv/com.fibaro#34]
When dimming the device using the slider it will return a float between 0.0-1.0.
In most drivers this is converted by `<value> * 100` which returns anything between 0 and 100.

The fibaro devices only accept 0-99 which results in devices not being turned on!
I created a pull request (#33) for the FGD-211 with an easy fix.

However it would make more sense if the slider would return 0-99 instead of the float.

**Comment by RobinBol** [comment]
Fixed!
