### ISSUE TITLE
[Enhancement] Control LED Ring color from wall plug through flow.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/com.fibaro#43]
As described above, it would be nice to have a function to select a colour on the Fibaro wall plug, regardless of the device state.

Example, at night, switch the LED ring in the hallway on (white) if you go to the toilet  and switch the LED Ring off again after 15 minutes. Or switch the LED Ring off during night, and have it switched on if your HUE lights are switched on.

Tried a little bit myself, but I haven't found out how to update settings for a Z-Wave device.

**Comment by caseda** [comment]
I've made it possible to control the LED ring with flow triggers.

They are not state independent though, it's not (easily) possible to do this, so there are 2 cards, for the on state and the off state.

Not yet a pull request, but you can still try it out if you know how to install apps via Git:
https://github.com/caseda/com.fibaro

**Comment by Arjanvde** [comment]
@caseda Wow, that looks really great!

I'm going to install this tonight and test it.  Really great job, think some other developers can use your code for the settings in their own apps.

**Comment by Arjanvde** [comment]
@caseda, works like charm. Thanks for your help!
