### ISSUE TITLE
[Enhancement] have the option to deselect S2 as it is not existing

### ISSUE THREAD

**Issue by Arjanvde** [athombv/com.fibaro#45]
Within my current setup in the hallway i'm using a Fibaro Relay to switch on/off the lights with a single button. I've added the Relay with the Fibaro app v1.0.8. but it also requires me to configure the S2 but this is not active.

Would it be an option to let the user decides if the S2 button needs to be configured? I don't need this in my current setup and would therefore like to see this to be an option.

**Comment by RobinBol** [comment]
In what way are you forced to configure the S2? As to my understanding, the relay adds two devices, one main node, and one for S2. If you do not want to use the S2 you can just remove the device.

**Comment by Arjanvde** [comment]
@RobinBol 

Where can i remove the S2 node? I don't see the remove button.

![s2](https://cloud.githubusercontent.com/assets/17526110/18540868/e19ee8e4-7b21-11e6-89f8-5ee1ab1d5746.jpg)

**Comment by RobinBol** [comment]
Ah I see, the problem is that the S2 node doesn't display a delete button in the top right corner on hover?

**Comment by Arjanvde** [comment]
Exactly, so i can't remove the node.

**Comment by RobinBol** [comment]
Thanks for the clarification, I will create a generic Homey issue for this as it is not specific to the Fibaro app.
