### ISSUE TITLE
FGMS-001 Z-Wave+ motion not triggered

### ISSUE THREAD

**Issue by ThaYoung1** [athombv/com.fibaro#49]
After a while motion sensor doesn't trigger flows anymore. Homey reset makes it work again for some time. After that it stops working again

**Comment by RobinBol** [comment]
What version of the app/Homey are you running? You could try to re-add the device with the latest app installed, can not reproduce your issue, got a FMGS-001 running here for quite some time.

**Comment by ThaYoung1** [comment]
I have re-added the device a couple of days ago. Seems to be working now. I'll close the issue
