### ISSUE TITLE
Smoke sensor v1 device items missing

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/com.fibaro#5]
Fibaro app version 1.0.2

I'm missing temperature, temper alarm

![screenshot_20160729-211917 2](https://cloud.githubusercontent.com/assets/15921016/17260734/4553ba92-55d2-11e6-9521-367dfebc5538.png)

And device specific settings like wake up interval:

![screenshot_20160729-211542 2](https://cloud.githubusercontent.com/assets/15921016/17260663/f7dc8f78-55d1-11e6-86fd-844172f708fa.png)

**Comment by Inversion-NL** [comment]
Started this myself.

Extra, device specific settings: https://github.com/Inversion-NL/com.fibaro/commit/ba339f3f99a39e626eca7c51b32113da1e1bd224
Temperature reading: https://github.com/Inversion-NL/com.fibaro/commit/23c2d70bf8bacdb6f454e770cb2faa23239bc1b2

Currently testing both, which will take a few days.

**Comment by WeeJeWel** [comment]
Added measure_temperature, alarm_tamper

**Comment by Inversion-NL** [comment]
Extra device settings awaiting in Pull Request #16
