### ISSUE TITLE
App crashes on saving settings in 2x1,5 relay subdevices

### ISSUE THREAD

**Issue by irritanterik** [athombv/com.fibaro#50]
App v1.0.9, Homey 0.9.3

After pairing a 2x1,5 relay 3 devices are added.
Settings must be changed on the 'root' device. This works ok.
But the two sub devices (S1, S2) also shows settings.
When changing and saving settings on these sub devices the Fibaro app crashes.

**Comment by caseda** [comment]
There was a small moment that the setting pages were gone on the sub devices, but apparently they are back (so weird...)

But i don't think it is just the fibaro app, this will need to change in the z-wave core to disable the settings pages of any sub devices

**Comment by RobinBol** [comment]
Created generic issue as this is not only applicable to the Fibaro app: https://github.com/athombv/homey/issues/857
