### ISSUE TITLE
FGRGBWM-441, RGBW Controller - Set colour by value

### ISSUE THREAD

**Issue by soler2000** [athombv/com.fibaro#51]
Would it be possible to add a card to the flow editor where the colour can be set by a variable or at least set to a specific value.  While the colour picker works ok, if there are multiple RGB controllers in a room it is near impossible to set the colour to an equal value on each device.

**Comment by Arjanvde** [comment]
@soler2000 

Check this post:

https://forum.athom.com/discussion/comment/25892/#Comment_25892

**Comment by soler2000** [comment]
Great thanks,    I did not see that setting
