### ISSUE TITLE
Add Flow cards for second button trigger on FGD-211

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/com.fibaro#52]
Support ticket: #655

```
Op de Fibaro FGD-211 kan een dubbele schakelaar worden aangesloten. 1 voor de last en 1 om een andere actie uit te voeren. Graag zou ik deze 2e knop ook terugzien in de Flows.
```

**Comment by mtudor** [comment]
There is currently a flow card for "S2 Switched" but this doesn't seem to respond when S2 is pressed.  The same is true of the "S2 Long Pressed/Double Pressed" card.  Is this a known bug?

**Comment by RobinBol** [comment]
The coming Fibaro app update will bring advanced Flow card functionality for both S1 and S2.
