### ISSUE TITLE
Cannot pair Fibaro Double Switch 2 (FGS-223)

### ISSUE THREAD

**Issue by nicoroosenboom** [athombv/com.fibaro#53]
When trying to pair my FGS-223, it's stuck at "Setting app-specific association groups...". Repeated the procedure a couple of times (remove node/add node), even executed a factory reset of Homey.

Homey v0.10.0 and Fibaro App v1.0.11 installed.

**Comment by RonaldArenz** [comment]
Same problem here, same configuration as well, but in Dutch language. Also 30 min PTP did not work, Switch is new. Other devices installed: Fibaro smoke detector, qubino zwave dimmer, Onkyo App, Panasonic App, Kodi app.

**Comment by caseda** [comment]
I have fixed this issue, but it does come at a cost thanks to a (hard to squish) bug in the homey core.
Only Switch 1 (S1/Q1) is able to be used by homey, switch 2 is not possible yet.
Will come in the next update.

**Comment by RobinBol** [comment]
@caseda could you give a quick comment on the homey core bug you mention that breaks the pairing?

**Comment by RobinBol** [comment]
Fixed!
