### ISSUE TITLE
Temp Sensor support for FGK-10x

### ISSUE THREAD

**Issue by alledijkstra** [athombv/com.fibaro#54]
I would like to see temperature support for the FGK-10x. I have several FGK-10x with temperature across the house.

**Comment by caseda** [comment]
Will be added in the next update, or if you can't wait, download my pull request.

**Comment by caseda** [comment]
has been added in 1.0.12+
can you confirm it works?
you will need to re include the module

**Comment by alledijkstra** [comment]
Working
