### ISSUE TITLE
FGFS-101: Apps crash on opening card 

### ISSUE THREAD

**Issue by alledijkstra** [athombv/com.fibaro#55]
I just included the Fibaro Floodsensor and opened the card. Right after that, the app crashed. 

Stack trace:
```
TypeError: Cannot read property 'CommandClass' of undefined
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:447:26
at Array.forEach (native)
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:431:23
at Array.forEach (native)
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:417:29
at /homey-app/wireless/zwave.js:53:12
at process.<anonymous> (/homey-app/helpers/client.js:1:1146)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12

Exit code: 0
```

**Comment by RobinBol** [comment]
Did you use the latest Fibaro app (1.0.11)? 

Do you have a temperature sensor connected?

What happens if you try again to include?

Strange because I tested with a flood sensor yesterday, everything fine.

**Comment by simmer1974** [comment]
Yes, i had the latest 1.0.11 and no temp sensor on the floodsensor. Everytime i include the device it crashed and open the Card it crashed. Even when i remove the device, the app keeps crashing. Had to remove and install the app again before i could include a fibaro device again.

**Comment by caseda** [comment]
The temp sensor is build in, so no extra attachment is needed.

what version of the fgfs-101 do you got, the z-wave + (plus) version or the normal version

Does the error still occure if you re-include it to homey

**Comment by caseda** [comment]
does this still crash in the newest update? (1.0.14)

**Comment by alledijkstra** [comment]
Robin is investigating this problem.

**Comment by alledijkstra** [comment]
Issue solved.
