### ISSUE TITLE
Multisensor Gen5 - Missing setting

### ISSUE THREAD

**Issue by zperx** [athombv/com.fibaro#57]
The parameter 8 and 9 is missing from the device settings:

8. Motion detection - operating mode
This parameter determines in which part of day the PIR sensor will be
active.
This parameter influences only the motion reports and associations.
Tamper, light intensity and temperature measurements will be still
active, regardless of this parameter settings.
Available settings: 0 - PIR sensor always active
1 - PIR sensor active during the day only
2 - PIR sensor active during the night only
Default setting: 0 Parameter size: 1 [byte]

9. Motion detection - night/day
This parameter defines the difference between night and day in terms
of light intensity, used in parameter 8.
Available settings: 1-32767 (1-32767 lux)
Default setting: 200 (200 lux) Parameter size: 2 [bytes]

**Comment by caseda** [comment]
these parameters have been added in the version that is live now (1.0.14)

**Comment by zperx** [comment]
Thanks
