### ISSUE TITLE
Can't pair fibaro dimmer 1

### ISSUE THREAD

**Issue by sizarkamar** [athombv/com.fibaro#58]
Since I updated to 0.10.0 I was not able anymore to pair my fibaro dimmer 1, I did a full recovery and tried many times to reset the power circuit and the z-wave receiver, but nothing helps. After updating to 0.10.1 i still have the same problem.
Every time it gives me the message: the interview has time out. No device has been found.

Some info from z-wave receiver:
Node ID: 1
SUC ID: 1
Power Level: 0

State:
{"zw_state":{"region":"AE","regions":{"CN":{"hardware":"AE","title":"China"},"EU":{"hardware":"AE","title":"European Union","active":true},"IN":{"hardware":"AE","title":"India"},"MY":{"hardware":"AE","title":"Malaysia"},"RU":{"hardware":"AE","title":"Russia"}},"activeFirmware":"EU","ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1],"chip_type":5,"chip_version":0,"homeId":3772300923,"nodeId":1,"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":true,"sucId":1,"powerLevel":0,"networkKey":"b1196af421d539c49b541c1760e209d9","methodsAsync":["addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes"]},"zw_ready":true}

**Comment by caseda** [comment]
I don't think that is a problem caused by homey but by the dimmer.
Have you reset the dimmer itself as well?

either via homey => Settings -> Z-Wave -> [Remove Device]
or module itself =>  Reset by holding B button for 3 sec. after connecting
mains voltage to the Dimmer

**Comment by sizarkamar** [comment]
Thank you for the answer caseda, the dimmer was working fine just before updating to 0.10.0.
if I select remove device, it still can't find the dimmer, but I'll try to reset the module itself, and will let you know.

**Comment by caseda** [comment]
If it still doesn't see the module when you enter inclusion/exclusion mode, i will have to ask (just like the solution of the other issue you responded on) what is the distance from homey to the dimmer?

**Comment by sizarkamar** [comment]
Thank you problem solved, it was solved by resetting the dimmer module itself. The distance was less then 2 meters
