### ISSUE TITLE
Motion sensor: parameters for movement do not work

### ISSUE THREAD

**Issue by Tweaqer** [athombv/com.fibaro#60]
I tried using some of the movement parameters:
![parameters](https://cloud.githubusercontent.com/assets/20989897/19221777/f61e900e-8e49-11e6-88ac-6880fabe18b5.png)
But I dont really see a change (after waking up the Fibaro Motion Sensor) for the following items:
- Bewegingssensor gevoeligheid
- Bewegingsalarm annuleringsperiode (seconden)

Also the description on the (i) isnt correct for:
- bewegings alarm functie drempel

**Comment by caseda** [comment]
what is wrong with the description?

and i tried to change the values of my normal (non Z-Wave+) sensor and they seem to go through correctly when looking at buffer value.

there is something odd about the motion sensitivity size, which states "2 bytes" even in the manual and and on other websites, but the values it's using only needs 1 byte of size.. that might be whats wrong.
it is 1 byte for the non z-wave version.. a manual mistake maybe.?
Will enclose more about this when i get some more (correct) information.

The cancellation delay should work properly.
Gets converted properly to the right value, have been playing around a bit and it seems to start (stop working) if the value goes above 90/100 seconds...
500 seconds = <Buffer 01 f4> so this is correct
@WeeJeWel this issue maybe something for you. /\

**Comment by Tweaqer** [comment]
I realize now that I've documented my issue poorly.
I also use a z-wave plus version and I use it in combination with a flow. This flow:
![beweging aan](https://cloud.githubusercontent.com/assets/20989897/19237151/97441b96-8efb-11e6-84bc-f314f79c3b81.PNG)
![beweging uit](https://cloud.githubusercontent.com/assets/20989897/19237153/9d27a6cc-8efb-11e6-81b2-67717a606464.PNG)
So what I want is by changing the 'annuleringsperiode' from 300 to 500 that the lights stay on longer.
Also here's a screenshot of the wrong description saying something about lux where this should be about movement:
![foutieve omschrijving](https://cloud.githubusercontent.com/assets/20989897/19237189/e2d01fec-8efb-11e6-86bc-23e784226d26.png)

**Comment by caseda** [comment]
it's kinda about motion, it's for when the motion alarm is active (day or night) and at which level of lux this should change (below 200 = night, above 200 = day).
Its corresponding with the same name above it... though it was pretty clear because of the same name.
But i'll change the description so this is more clear.

the motion sensitivity i'm waiting for a definitive answer, this doesn't come from athom but from fibaro itself so who knows when it will come.

and like i explained the value is being send through properly, it doesn't matter if it is the + or non + version, the script for this is the same (i already knew you had the + version).
its just that maybe the value is not being send to the sensor(s) properly or its not being received by the sensor properly, this isn't something the app can change.

**Comment by WeeJeWel** [comment]
I've viewed the network on the Z-Wave Sniffer and all values are applied properly.

**Comment by caseda** [comment]
@WeeJeWel did you also check the motion cancellation delay? the one i really asked for 😅

**Comment by WeeJeWel** [comment]
Yep, works fine!

![screen shot 2016-10-11 at 12 59 51](https://cloud.githubusercontent.com/assets/319873/19268092/9f046446-8fb2-11e6-9cb9-7f2bf038cc00.png)

**Comment by caseda** [comment]
awesome, thanks a bunch, now we at least know it's not homey that is causing the issue.. will see if i can find anything more about why this happens

**Comment by caseda** [comment]
@Tweaqer i found the issue, it is the sensor itself not receiving the signal fully properly.

I tried to find a reliable way to send the parameters to the sensor:
(got it working with many different values about 7 times)

1. edit the parameters you want to but **_don't_** save just yet.!
(so if you want to use the 500 seconds, and it is still on 500 change it to something else, save, then change it back but **don't** save this value yet.!)

2. wake up your sensor close to homey, and only then click the save button (within 2-3 seconds)
now it should give the notification "Device settings saved." and it should have set the parameters properly onto the sensor

if it gives the notification: "Settings will be saved when the device on batteries is active".
something went wrong and try to wake up the sensor within a few seconds so it still will be received pretty quickly (not confirmed).
or start over with the settings.

**Comment by caseda** [comment]
the parameter description will be changed in the next pull request.

**Comment by Tweaqer** [comment]
You are a lifesaver caseda, this worked for me, the timer now uses 500 seconds :)
