### ISSUE TITLE
Fibaro Door/Window FGK Firmware 2.1 not including

### ISSUE THREAD

**Issue by gajdur** [athombv/com.fibaro#71]
First i tryed with one FGK Firmware 2.1 Sensor but without success, not including at all: Waiting for zwave device. Now bought two more, received Firmware 2.1 to. Not including also.

Now i'm sure that the sensor is not defective, is homey not including the sensors.

Please add support for this Sensor.

**Comment by caseda** [comment]
how are you trying to include it, because if it was not supported it would still include but as a "generic device"
what is the distance you are trying to include it as well

**Comment by gajdur** [comment]
Hi caseda, tryed over Fibaro App and as Zwave device. Nothing happens, not recognised, distance 15-20cm.

**Comment by caseda** [comment]
So you removed the tag at the battery, closed the case again, started the inclusion inside homey (devices - > + new device - > fibaro - > door/window sensor) 
Then pressed the button on the back 3 times?

**Comment by gajdur** [comment]
Yes, i have already 10 door sensors 2.5 working. The last hours tryed with reseting, and retrying. Now worked with one of them, but after continuously pressing the tmp button on the bottom.

**Comment by caseda** [comment]
hmm, have you ever added them before to homey? maybe the resetting doesn't go well, did you try to reset the module with homey's settings -> Z-Wave -> [Remove Device] ?
or did you try to reset it manually on the sensor itself

**Comment by posthok** [comment]
Having the same problem. Updated to the latest firmware and trying again to move from domoticz to Homey again. But the door sensor do not pair with Homey. Also did a reset on the sensor

**Comment by gajdur** [comment]
Resetted both ways, sensors are new.They are included now, after multiple try and multiple clicks( not only three times). Only one of them is sending the status.

**Comment by caseda** [comment]
it can indeed happen that you need to click multiple times (more then 3) this is a problem of the sensor and not homey, it's related that the clicks need to be really close after each other.

But only 1 sending status seems like it's not an app problem, either try looking to association groups, there should be a "1" (without quotes) in group 3.
if not add the 1 and save while the sensor is awake manually. (so awake first, then save).

if there is a 1 already, try re-adding it to homey, maybe something went wrong during pairing.

if that still doesn't work, let it rest for at least 2 hours, if it then still does not work, it's your sensor that doesn't work

**Comment by RobinBol** [comment]
It might also be a range issue.

As this issue is concerned with the pairing problem, which seems to be solved, I will close this issue for now.
