### ISSUE TITLE
FGS-223: Remove settings from multiChannelNode 

### ISSUE THREAD

**Issue by RobinBol** [athombv/com.fibaro#74]
The second device should not have any device settings, changing those will crash the app.

**Comment by caseda** [comment]
not fibaro related, but i guess the issue is general: if pollinterval is defined it does need to be shown in the endnodes (related to for example greenwave app, the node 6)

**Comment by RobinBol** [comment]
True, but this can be done by adding the (pollInterval) setting objects to the array of the settings of the multichannelnode.
