### ISSUE TITLE
no temperature reading for motion sensor

### ISSUE THREAD

**Issue by goyaweb** [athombv/com.fibaro#75]
I would like to be able to read the latest temperature setpoint from the "and" column condition card from the motion sensor (non-zwave plus).

**Comment by caseda** [comment]
Use the temperature is changed trigger with the logic in the and column?

Otherwise make this an general issue so it can be added to the capability,  not going to happen on app level

**Comment by goyaweb** [comment]
sorry, don't get how to get temperature the way you suggest. Which card do I put in the and column then to read most recent temp point?

**Comment by caseda** [comment]
![naamloos-1](https://cloud.githubusercontent.com/assets/2565450/20608682/35c27fa0-b284-11e6-902b-c1f3f847d935.jpg)

**Comment by caseda** [comment]
when global variables arrive, there will (should) be a default variable with temperatures for every room

**Comment by RobinBol** [comment]
Thanks @caseda , I will consider this issue fixed for now, it will however be improved in the future indeed.
