### ISSUE TITLE
Dimmer 2 on/off on boot

### ISSUE THREAD

**Issue by MarcelAkerboom** [athombv/com.fibaro#82]
Once Homey boots, and inquires the state of the z-wave devices, the _Dimmer 2_ devices do not send on/off state. So in the mobile card, the state shows as off, with dim slider at x%.

Possible fixes:
- Query for on/off state. 
- Infer from dim > 0 that state is on.

Below the state's homey receives from my devices on boot:
"Woonkamer eettafel" and all "spot's" are dimmers.

> 2016-12-13T17:52:54.588Z	Woonkamer eettafel	["dim",0.21]
> 2016-12-13T17:52:52.842Z	Garderobe spot	["dim",0.99]
> 2016-12-13T17:52:34.051Z	Slaapkamer boven licht	["dim",0.01]
> 2016-12-13T17:52:34.035Z	Aanrecht strip	["dim",0.56]
> 2016-12-13T17:52:28.743Z	Aanrecht strip	["measure_power",9.7]
> 2016-12-13T17:52:27.653Z	Aanrecht strip	["light_temperature",0.57]
> 2016-12-13T17:52:26.682Z	Slaapkamer boven licht	["measure_power",0.1]
> 2016-12-13T17:52:26.654Z	Slaapkamer boven licht	["light_temperature",0]
> 2016-12-13T17:52:26.622Z	Aanrecht strip	["light_hue",0]
> 2016-12-13T17:52:26.604Z	Aanrecht strip	["onoff",true]
> 2016-12-13T17:52:26.596Z	Slaapkamer boven licht	["light_hue",0.67]
> 2016-12-13T17:52:24.550Z	Slaapkamer boven licht	["light_hue",0]
> 2016-12-13T17:52:24.511Z	Slaapkamer boven licht	["onoff",true]
> 2016-12-13T17:52:22.290Z	Woonkamer eettafel	["meter_power",1.07]
> 2016-12-13T17:52:21.119Z	Woonkamer eettafel	["measure_power",50.9]
> 2016-12-13T17:52:17.833Z	Garderobe spot	["meter_power",0.21]
> 2016-12-13T17:52:16.246Z	Garderobe spot	["measure_power",6.1]
> 2016-12-13T17:52:14.627Z	Verwarming	["measure_humidity",45]
> 2016-12-13T17:52:14.622Z	Verwarming	["measure_temperature",20.5]
> 2016-12-13T17:52:14.604Z	Verwarming	["target_temperature",20.5]
> 2016-12-13T17:52:14.602Z	Verwarming	["available",null]
> 2016-12-13T17:52:13.439Z	Entree spot	["meter_power",0.18]
> 2016-12-13T17:52:12.431Z	Chrome Woonkamer	["available",null]
> 2016-12-13T17:52:12.355Z	Entree spot	["measure_power",4]
> 2016-12-13T17:52:11.681Z	Verwarming	["unavailable","Verbinden..."]
> 2016-12-13T17:52:11.218Z	Aanwezigheid	["onoff",true]
> 2016-12-13T17:52:11.146Z	Nachtprogramma	["onoff",false]
> 2016-12-13T17:52:08.934Z	Toilet beneden spot	["meter_power",0.04]
> 2016-12-13T17:52:07.379Z	Toilet beneden spot	["measure_power",0]
> 2016-12-13T17:52:06.515Z	Woonkamer Telelamp	["measure_power",131.1]
> 2016-12-13T17:52:05.753Z	Was & Droger	["measure_power",0]
> 2016-12-13T17:52:03.715Z	Smart Switch 2	["measure_power",0]
> 2016-12-13T17:52:00.960Z	Was & Droger	["onoff",true]
> 2016-12-13T17:51:59.362Z	BeNext P1 Dongle	["meter_gas",0]
> 2016-12-13T17:51:59.244Z	BeNext P1 Dongle	["meter_power.low",346.87]
> 2016-12-13T17:51:58.323Z	BeNext P1 Dongle	["meter_power.normal",372.79]
> 2016-12-13T17:51:57.691Z	BeNext P1 Dongle	["measure_power",779]
> 2016-12-13T17:51:30.033Z	Start device listener	"Will listen to realtime events of 30 devices"

**Comment by RobinBol** [comment]
I have tested several times, and Homey does query the device for its on/off state, and during testing it never failed to retrieve that state. So my guess is that your device does not respond to the on/off query by Homey. Perhaps you could try to re-pair the device.
