### ISSUE TITLE
FGMS-001 doesn't report at all

### ISSUE THREAD

**Issue by sossienl** [athombv/com.fibaro#83]
It worked for a while, but looking at my flows (that aren't triggered) and the insights sections. the Fibaro sensor doesn't report anything anymore.

I have an other sensor (3+ year old) that reports perfectly. See screenshots. The green line is the Fibaro sensor; showing temperature in green. 

<img width="586" alt="screen shot 2016-12-14 at 17 51 38" src="https://cloud.githubusercontent.com/assets/609650/21191617/01f26422-c226-11e6-91ea-12597d819399.png">
<img width="328" alt="screen shot 2016-12-14 at 17 51 30" src="https://cloud.githubusercontent.com/assets/609650/21191615/01f15b54-c226-11e6-9e5d-b3df30f64208.png">
<img width="789" alt="screen shot 2016-12-14 at 17 46 53" src="https://cloud.githubusercontent.com/assets/609650/21191616/01f25284-c226-11e6-8963-c5aa97f53523.png">

**Comment by sossienl** [comment]
Seems like the device stopt reporting at 12th of December around 7:50 AM. 

Running Homey version 1.0.3

**Comment by RobinBol** [comment]
Homey version 1.0.4. will likely fix this issue, if it doesn't please let me know!

**Comment by sossienl** [comment]
I updated #1159 with my results after updating to 1.0.4 and Fibaro app 1.1.6. Still not working as expected

**Comment by chrisboer** [comment]
I have the same issue with the range reduced 50 % on FGS222 after 1.0.3 Firmware of Homey.
When is version 1.0.4 expected ?

**Comment by RobinBol** [comment]
Considering your device is reporting, will continue this discussion in https://github.com/athombv/homey/issues/1159
