### ISSUE TITLE
Push Button FGPB-101 no longer working

### ISSUE THREAD

**Issue by aljoen** [athombv/com.fibaro#88]
After Homey FW update 1.1.0 (and 1.1.2) update and Fibaro 1.1.7 update,  push buttons FGPB-101 seems no longer to work. Had this with both my buttons. Re-pairing, PTP  did not solve this issue either.

**Comment by RobinBol** [comment]
Thanks for reporting, will look at it asap!

**Comment by caseda** [comment]
@RobinBol you made a typo in the configuration -> flow - > trigger for FGPB it's now FGBP

**Comment by aljoen** [comment]
@caseda thanks. Good to know this is a "simple" thing to rectify

**Comment by RobinBol** [comment]
Oh wow, been looking at those device codes for so long I couldn't really tell the difference..

Could not test whether this really resolves your issue (as I don't have the device with me), but it is very likely so I went ahead and pushed the update (v1.1.8) to the app store, please let me know whether it works for you now!

**Comment by aljoen** [comment]
I updated to 1.1.8 but even after a PTP no joy. Tried to re-pair the button but interview failed, got stuck on security key exchange...twice..

**Comment by RobinBol** [comment]
Re-pair might be needed indeed, failing interview should not be related. So if you get the device paired and it is still not working then something else is up and I'll investigate coming week.

**Comment by caseda** [comment]
renaming shouldn't be the fix for the issue, the code in app.json stays the same, only the placement changes was just something i noticed 😄
re-add might help with the previous update that happend

**Comment by caseda** [comment]
found the issue, the CC parser changed thanks to the latest core update to support v3 of central scene CC (the way the button works) i will update the driver in a few seconds :+1:

**Comment by RobinBol** [comment]
Oh! Good catch:)

**Comment by caseda** [comment]
the update that battery is now auto gotten on online, can over saturate homey with the button 😅 just gotten 5 battery reports on 1 push of the button

**Comment by aljoen** [comment]
Thanks. That maybe also explains why button is difficult to re-add....will try again when update available

**Comment by caseda** [comment]
@RobinBol the `battery report` really messes up the central scene reporting of the button,
some just become the `battery report` instead of the `central scene notification`, like it overwrites the command.
and is also indeed the case for trying to remove the button from homey

it even gets send when the `'command_get'` is not there

if you could debug this issue afterwards somewhere since i have no clue why it does this
it gets better over time the app is running, but is just really weird
can create a separate issue for this later if you rather have that

**Comment by RobinBol** [comment]
Well, the driver doesn't perform a get on the battery, only on start up.

I have been debugging, and it seems the device is just malfunctioning. Homey never performs any get, but every time the button is pressed the button sends a battery report to Homey, and never a scene activation.

**Comment by caseda** [comment]
before homey FW 1.0 (somewhere) it was never the case, but like i said, maybe both signals are send, but only one triggers inside homey on the listening channel.

since it becomes better when the app is running for a minute (central scene then does comes in)

**Comment by RobinBol** [comment]
No, only battery reports are send (I can sniff(a)). App been running here for 10 minutes, still no central scene reports..

**Comment by caseda** [comment]
then how did i get the central scene's without sniffer 😲 😝

**Comment by RobinBol** [comment]
Wel, after pairing I manage to receive one central scene, but thats it, then it is flooded with battery reports.

**Comment by caseda** [comment]
hmm, has been working for me pretty consistently with triggering since i rewrote the drive, so it is kinda weird.

another bad fibaro product even though it has gotten an award 😲

**Comment by chrisboer** [comment]
It worked for me untill Homey 1.0.5 was upgraded to 1.1.2 I believe. I was already running on fibaro 1.1.8 and still the button reacted as it should. 

Now I don't get any respons but I already re-paired it but still no activation when again put in a flow.

**Comment by RobinBol** [comment]
Well, I'll merge your PR, but I can not verify that it works due to the malfunctioning device over here..

**Comment by caseda** [comment]
there was someone else (forgot the name real quick) that used the pr and got it working as well :+1: so at least i'm not the only one

**Comment by RobinBol** [comment]
Merged your PR, should resolve this issue.

**Comment by chrisboer** [comment]
Yeessssss It works again... you guys are the best
