### ISSUE TITLE
[Reminder] FGR(M)-222/FGR-221 still needs percentage control

### ISSUE THREAD

**Issue by caseda** [athombv/com.fibaro#89]
Just a small reminder that this still needs to be implemented, (MultiLevel Switch)
since i have no clue how i should handle this.
and since i don't have the device myself it's kinda hard to implement it at all.

**Comment by gajdur** [comment]
Any news here?

**Comment by RobinBol** [comment]
@gajdur which of these devices do you have? We have them at the office, but I can not properly test it on a live roller shutter. I could create the functionality for the device(s) you own and let you test it?

**Comment by gajdur** [comment]
Hi @RobinBol , and tnx.

I am ready to test, cli install is also no problem.

I have FGR-222, v2.5, 
Infos from Homey Device: Manufacturer 271, Type ID 769, Product 4097.

**Comment by RobinBol** [comment]
@gajdur great, just added the dim functionality to the fgr-222 on this branch: https://github.com/athombv/com.fibaro/tree/fgr-222-dim. Note; it is untested, please let me know what happens!

**Comment by gajdur** [comment]
@RobinBol if is not working, can i go back to the master branch? Im not loosing my fibaro devices with this install, or?

Tnx

**Comment by gajdur** [comment]
newer mind, no risk no fun. installed and going to test.

**Comment by RobinBol** [comment]
You can install this test version of the app over the current version, if you are done just install the master branch app over the test version again. (testing is at your own risk, nothing should happen though if you just use athom project --run).

**Comment by RobinBol** [comment]
Great and thanks, keep me posted:)

**Comment by gajdur** [comment]
Hi @RobinBol , no success. Fibaro App is crashing and making Homey extrem slow. Now after a new reinstall of the App and waiting for 2 hrs. is crashed again and i have this message:
Stack trace:

Error: Callback was already called.
at /node_modules/homey-zwavedriver/node_modules/async/dist/async.js:840:32
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:157:5
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:493:51
at Array.forEach (native)
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:485:23
at Array.forEach (native)
at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:471:29
at /homey-app/wireless/zwave.js:53:12
at process.<anonymous> (/homey-app/helpers/client.js:1:1269)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:721:12
at nextTickCallbackWith0Args (node.js:436:9)
at process._tickCallback (node.js:365:13)

Exit code: 1
Exit signal: null

Im not at home atm to control the complete output from the console.

**Comment by gajdur** [comment]
9AF1537922 is the Log from Homey.

**Comment by nlrb** [comment]
I have 2 FGR-221 modules (1 connected to a roller shutter, 1 new spare). Z-wave [product ID: 38](http://products.z-wavealliance.org/products/38) (productTypeId: 258). Anything I can do to help add and test?

**Comment by RobinBol** [comment]
@gajdur could you try to get the latest version from https://github.com/athombv/com.fibaro/tree/fgr-222-dim and try to test it again? I've added some fixes.

@nlrb we do not have support for the older FGR-221 at the moment, only FGR-222.

**Comment by gajdur** [comment]
hi @RobinBol running the new files, but i dont see the dim capability.

**Comment by RobinBol** [comment]
Did you re-pair the device?

**Comment by gajdur** [comment]
eh, no. trying now without taking it from the wall.

**Comment by caseda** [comment]
@gajdur you can enable the exclusion/inclusion mode with the switch that is attached to S1, switching it 3 times is the same as pushing the button 3 times

**Comment by gajdur** [comment]
@caseda no success with s1 (up) and the first relay. Taking it out now. After repair i see the dim slider and going to try now.

**Comment by RobinBol** [comment]
With help from @gajdur FGR-222 now has the dim capability as well. Will close this issue.
