### ISSUE TITLE
Fibaro Motion Sensor (non Z-Wave+) device specific settings not accepted to be changed

### ISSUE THREAD

**Issue by jeroenvano** [athombv/com.fibaro#91]
Hi When I change the Fibaro Motion Sensor (non Z-Wave+) device specific settings they do not get updated and changed. Examples are changing settings for blind time or alarm cancel time. Also Led collor settings do not get changed when the motion sensor wakes up.

**Comment by RobinBol** [comment]
Hi, thanks for reporting, please see https://github.com/athombv/com.fibaro/issues/70
