### ISSUE TITLE
Feature request Dimmer 2 - trigger card for energy changed

### ISSUE THREAD

**Issue by jeroenvano** [athombv/com.fibaro#92]
In some flow scenario's it would be nice to have a "energy changed" trigger card available for the Dimmer 2 devices. Tags are available today to be used in logic but I am missing the trigger card to execute the flow.

Regards, Jeroen

**Comment by RobinBol** [comment]
@WeeJeWel this is a device of class `light`, with capabilities `measure_power` and `meter_power`. These should also have the flow cards for these capabilities right?

**Comment by caseda** [comment]
class light doesn't have these capabilities, also the reason why we added a custom mobile card to the dimmer 2.
but that of course only works for the mobile card

**Comment by RobinBol** [comment]
I know, but therefor I propose to add these capabilities to class light as there are many devices that can do this. Now a user has to choose between light functionality (like speech) and the flow cards (when adding it as other e.g.).

**Comment by caseda** [comment]
we did that months ago 😱

**Comment by RobinBol** [comment]
Created an issue in the Homey issue tracker for this, as this is best fixed in homey-client: https://github.com/athombv/homey/issues/1846
