### ISSUE TITLE
Cant dim on a dimmer 2

### ISSUE THREAD

**Issue by PatrickSannes** [athombv/com.fibaro#98]
Currently I'm experiencing problems with the fibaro dimmer 2. Dimming from the device works as it should, but dimming in the flows does not.
What situation is:
- The lamp is on and dimmed at .76
- A flow is triggered to dim the value to .16
In the log I see first:
017-01-11T17:57:13.201Z Keuken ["dim",0.16]
And then I see a little later:
2017-01-11T17:57:13.532Z Keuken ["dim",0.76]

In effect, the lights are dipping for a short second to a lower brightness and then go back to its original brightness.

**Comment by RobinBol** [comment]
As you already know by now (I think) this will be solved by means of a capabilityOption for the dim capability.

**Comment by PatrickSannes** [comment]
Yep, that was what I heard. I hope that will not take long, its really frustrating now to get a good mood like this: https://youtu.be/HbH2CWb53iU?t=197

**Comment by RobinBol** [comment]
I understand, will release an update of the Fibaro app as soon as this feature is available.

**Comment by PatrickSannes** [comment]
Hope it will be implemented soon. Understood from Jeroen it could be done as a non breaking feature. Instead of one button to go to chill mode I still have to do many actions.

**Comment by jaimevisser** [comment]
Seen this happen on one of my dimmers as well.

**Comment by ericjanvanputten** [comment]
got it here as well

**Comment by caseda** [comment]
this should be fixed in app version 1.2.0 (now published) if you are on homey FW >= 1.1.9

**Comment by jaimevisser** [comment]
On homey 1.1.9, fibaro app 1.2.1. Confirmed that the dimmers seem to work again. Great job!

**Comment by RobinBol** [comment]
Thanks for the feedback!
